[#computer-basics]
== Noções básicas de informática
:imagesdir: chapters/computer-basics/images

[quote, Pablo Picasso]
____
Computers are useless. They can only give you answers.
____

=== Problema: Comprando um computador

Começamos quase todos os capítulos deste livro com um problema motivador.
Por quê? Às vezes, ajuda ver como as ferramentas podem ser aplicadas para entender
por que são úteis. À medida que avançamos em cada capítulo, abordamos os conceitos básicos
necessários para resolver o problema na seção *Conceitos*, os
detalhes técnicos específicos (geralmente na forma de sintaxe Java) necessários
na seção *Sintaxe* e, por fim, a solução para
o problema nas seções *Solução*. Se você não estiver interessado no
problema, tudo bem! Fique à vontade para pular para <<Conceitos: Hardware e software>> sobre hardware e software
ou para <<Sintaxe: Representação de dados>> sobre representação de dados, especialmente se você
já tiver alguma experiência em programação. Então, se quiser ver
outro exemplo detalhado, a solução para este problema está disponível em <<Solução: Comprando um computador>> como referência.

Vamos começar com um problema que não tem a ver com programação e que talvez
lhe seja familiar. Imagine que você está prestes a entrar na faculdade e precisa de um
computador. Deveria comprar um Mac ou um PC? Que tipo de computador vai
executar os programas mais rápido? Será que alguns tipos de computadores travam mais do que outros?
Por quais recursos vale a pena pagar mais? Por que há tantos
termos da moda e tanto jargão incompreensível associados à compra de um
computador?

Quando muitas pessoas ouvem “ciência da computação”, essas costumam ser as primeiras
perguntas que vêm à mente. A maior parte deste livro trata da programação
de computadores em uma linguagem chamada Java e *não* dos computadores
em si. Tentamos apresentar todo o material de forma que praticamente qualquer tipo
de computador possa ser usado na programação dos problemas e exemplos.
No entanto, tanto o hardware que compõe o seu computador quanto o
outro software em execução nele afetam a maneira como os programas que você escreve funcionam.

=== Conceitos: Hardware e software

Os computadores estão por toda parte. Nós os vemos em quase todos os lugares. Eles estão presentes
na maioria das casas, lojas, carros, aviões, telefones e dentro de muitos outros
dispositivos. Às vezes, são visíveis, como um laptop sobre uma mesa,
mas a maioria dos computadores fica oculta dentro de outros dispositivos, como um relógio ou uma
televisão de tela plana. Os computadores podem ser máquinas complexas ou relativamente simples.
Apesar de sua diversidade, podemos pensar em todos os computadores em
termos de seu _hardware_ e do _software_ que nele é executado.

==== Hardware

O hardware consiste nos componentes físicos que compõem um computador, mas
não nos programas ou dados armazenados nele. Os componentes de hardware podem ser vistos
e tocados, se você estiver disposto a abrir o gabinete do computador. Uma maneira de
organizar o hardware é dividi-lo em três categorias: o
processador, a memória e os dispositivos de entrada e saída (E/S).

Essa visão de um computador é uma versão simplificada do que é chamado de
arquitetura von Neumann ou computador de programa armazenado. É um bom (mas
imperfeito) modelo da maioria dos computadores modernos. Nesse modelo, um programa (uma
lista de instruções) é armazenado na memória. O processador carrega o
programa e executa as instruções, algumas das quais exigem que o
processador faça muitos cálculos. Às vezes, o processador lê
dados da memória ou grava novos dados nela. Periodicamente, o
processador pode enviar saída para um dos dispositivos de saída ou receber entrada
de um dos dispositivos de entrada.

Em outras palavras, o processador pensa, a memória armazena e os dispositivos de E/S
se comunicam com o mundo exterior. O processador fica entre a
memória e os dispositivos de E/S. Vamos examinar essas categorias mais detalhadamente.

.Componentes de hardware em um computador desktop típico categorizados em CPU, memória e dispositivos de E/S.
image::vonNeumann.svg[scaledwidth=100%,pdfwidth=100%,width=100%]

===== CPU

O processador, ou unidade central de processamento (CPU), é o "`cerebro`" de um computador.
Ele recebe instruções, as decodifica e as executa. Ele pode enviar ou receber informações
das memórias ou dispositivos de entrada e saída (E/S). A CPU, em quase todos os computadores
modernos é um _microprocessador_, significando que toda computação é realizada por um circuito
integrado fabricado em silício. Quais são as características importantes em uma CPU? Como medimos
sua velocidade e potência?

[horizontal]
Frequência::
A velocidade de uma CPU (e de um computador como um todo) é geralmente
apresentada em gigahertz (GHz). Hertz (Hz) é a unidade de medida de 
frequência. Se alguma coisa acontece uma vez por segundo, então sua 
frequência é exatamente 1 Hz. Talvez o ponteiro de segundos do seu 
relógio se mova numa frequência de 1 Hz.Na América do Norte, a corrente 
nas tomadas alternam  com uma frequência de 60 Hz. O som também pode 
ser medido pela sua frequência. O som mais grave que um ouvido humano pode 
ouvir é de cerca de 20 Hz. O som mais agudo é cerca de 20.000 Hz. Um som 
como esse pulsa contra o seu tímpano 20.000 vezes por segundo. Parece 
muito, mas muitos computadores modernos operam em uma frequência de 1 a 4 
gigahertz. O prefixo "`giga`" significa "`bilhão`". Portanto, estamos 
falando de computadores realizando *algo* mais de um bilhão (1.000.000.000) 
de vezes por segundo.
+
Mas *o que* eles estão fazendo? Essa frequência é a _frequência de 
clock_, que indica a frequência que um sinal elétrico passa pela CPU. 
Em cada ciclo, a CPU realiza algum cálculo. Quanto? Depende. Em alguns 
sistemas, simples instruções (como somar dois números) pode ser computada 
em um único ciclo de clock. Outras instruções podem levar dez ou mais 
ciclos. Diferentes projetos de processadores podem levar diferentes números 
de ciclos para executar as mesmas instruções. As instruções também são 
executadas em _pipeline_, o que significa que uma instrução está sendo 
executada enquanto outra está sendo buscada na memória ou decodificada. 
Diferentes processadores podem ter maneiras diferentes de otimizar esse 
processo. Devido a essas diferenças, a frequência de um processador, 
medida em gigahertz, não é uma maneira precisa de comparar a velocidade 
efetiva de um processador com a de outro, a menos que os dois processadores 
sejam muito semelhantes. Mesmo que não faça muito sentido, a frequência do 
clock é comumente anunciada como a velocidade de um computador.
Tamanho da palavra::
Talvez você já tenha ouvido falar de computadores de 32-bit ou 64-bit. Como
nós falamos sobre no subtópico sobre memórias, um bit é um 0 ou um 1, a menor
quantidade de informação que pode ser armazenada. A maioria dos novos computadores 
são 64-bit, o que significa que eles operam a 64 bits por vez e podem utilizar valores
de 64-bit como endereços de memória. As instruções que eles executam nofmalmente
performam em quantidades de 64-bit, ou seja, números compostos de 64 0s e 1s. O tamanho
dos dados que um computador pode operar com uma única instrução é conhecido como _tamamnho 
da palavra_.
+
Em operações do dia-a-dia, o tamanho da palavra não é importante para a
maioria dos usuátios. Certos programas que interagem diretamente com  o 
hardware, como sistemas operacionais, podem ser influenciados pelo tamanho 
da palavra. Por exemplo, a maioria dos sistemas operacionais de 32-bit foram 
desenvolvidos para funcionar em um processador de 64-bit, mas a maioria dos 
sistemas operacionais de 64-bit não funcionam em processadores 32-bit.
+
Programas normalmente são executdos com maior velocidade em máquinas com
um tamanho da palavra maior, mas normalmente consomem mais memória. Um 
processador de 32-bit (ou sistema operacional) não pode usar mais de 4 
gigabytes (definido abaixo) de memória. Assim, um computador de 64-bit
é necessário para aproveitar a grande quantidade de memória que existem
hoje.
Cache::
O cérebro humano realiza cálculos e armazena informações. A CPU de um 
computador realiza cálculos, mas, na maioria das vezes, não armazena 
informações. O cache da CPU é a exceção. A maioria das CPUs modernas 
possui uma seção pequena e muito rápida de memória integrada diretamente 
ao chip. Ao prever quais informações a CPU utilizará em seguida, ela pode 
pré-carregá-las no cache e evitar a espera pela memória normal, que é mais 
lenta.
+
Com o tempo, os caches se tornaram mais complexos e, muitas vezes, possuem 
vários níveis. O primeiro nível é muito pequeno, mas incrivelmente rápido. 
O segundo nível é maior e mais lento. E assim por diante. Seria preferível 
ter um cache de primeiro nível grande, mas memória rápida é memória cara. 
Cada nível é maior, mais lento e mais barato que o anterior.
+
O tamanho do cache não é um recurso da CPU amplamente divulgado, mas faz uma 
enorme diferença no desempenho. Um processador com um cache maior pode 
frequentemente superar um processador que é mais rápido em termos de frequência 
de clock.
Núcleos::
A maioria do notebooks e computadores de mesa disponíveis hoje possui processadores _multicore_.
Esses processadores contêm dois, quatro, seis ou até mais núcleos. Cada núcleo
é um processador capaz de executar instruções de forma independente, e
todos eles podem se comunicar com a mesma memória.
+
Em teoria, ter seis núcleos poderia permitir que seu computador funcionasse seis vezes
mais rápido. Na prática, esse aumento de velocidade é difícil de alcançar. Aprender como
obter mais desempenho de sistemas multicore é um dos principais
temas deste livro. <<concurrency#concurrency, Concorrência>> e 
<<synchronization#synchronization, Sincronização>>, bem como as seções 
marcadas com *Concorrência* em outros capítulos, são especificamente
adaptadas para alunos interessados em programar esses sistemas multicore
para que funcionem de maneira eficaz. Se você não estiver interessado em 
programação concorrente, pode pular esses capítulos e seções e usar este
livro como um manual introdutório tradicional de programação Java. Por outro
lado, se você estiver interessado na área cada vez mais importante
da programação concorrente, <<Concurrency: Multicore processors,Concorrência: Processos Multicores>>
perto do final deste capítulo é a primeira seção *Concorrência* do
livro e discute os processadores multicore mais profundamente.

===== Memory

A memória é onde todos os programas e dados de um computador são armazenados. A memória de um computador geralmente não é um único componente de hardware. Em vez disso, as necessidades de armazenamento de um computador são atendidas por diversas tecnologias.

No topo da pirâmide da memória está o armazenamento primário, a memória que a CPU pode acessar e controlar diretamente. Em computadores de mesa e portáteis, o armazenamento primário geralmente assume a forma de memória de acesso aleatório (RAM). Ela é chamada de memória de acesso aleatório porque leva o mesmo tempo para acessar qualquer parte da RAM. A RAM tradicional é volátil, o que significa que seu conteúdo é perdido quando a energia é desligada. Todos os programas e dados devem ser carregados na RAM para serem usados pela CPU.

Depois do armazenamento primário vem o armazenamento secundário. O campo do armazenamento secundário é dominado por discos rígidos que armazenam dados em pratos magnéticos giratórios, embora a tecnologia flash esteja começando a substituí-los. Unidades ópticas (como CD, DVD e Blu-ray) e as unidades de disquete, agora praticamente obsoletas, também se enquadram na categoria de armazenamento secundário. O armazenamento secundário é mais lento que o primário, mas é não volátil. Algumas formas de armazenamento secundário, como CD-ROM e DVD-ROM, são somente de leitura, mas a maioria é capaz de ler e gravar.

Antes de podermos comparar esses tipos de armazenamento de forma eficaz, precisamos ter um sistema para medir a quantidade de dados que eles armazenam. Nos computadores digitais modernos, todos os dados são armazenados como uma sequência de 0s e 1s. Na memória, o espaço que pode conter um único 0 ou um único 1 é chamado de bit, que é a abreviação de “binary digit”(dígito binário).

Um bit é uma quantidade minúscula de informação. Para fins organizacionais, chamamos uma sequência de oito bits de byte. O tamanho em palavras de uma CPU é de dois ou mais bytes, mas a capacidade de memória é geralmente listada em bytes, não em palavras.

.Aqui é mostrada uma palavra que contém quatro bytes, ou 32 bits. Os cientistas da computação costumam numerar os itens a partir do zero, como discutimos em <<arrays#arrays>>.
image::bitsBytesFigure.svg[scaledwidth=100%,pdfwidth=100%,width=100%]

Tanto a capacidade de armazenamento primário quanto a secundária tornaram-se tão grandes que é inconveniente descrevê-las em bytes. Os cientistas da computação adotaram prefixos da física para criar unidades adequadas.

Unidades comuns para medir memória são bytes, kilobytes, megabytes, gigabytes e terabytes. Cada unidade é 1.024 vezes maior que a unidade anterior. Você deve ter notado que 210 (1.024) é quase igual a 103 (1.000). Às vezes, não fica claro qual valor se refere. Os fabricantes de unidades de disco sempre usam potências de 10 quando indicam o tamanho de seus discos. Assim, um disco rígido de 1 TB pode armazenar 1012 (1.000.000.000.000) bytes, e não 240 (1.099.511.627.776) bytes. Organizações de padronização têm defendido que os termos kibibyte (KiB), mebibyte (MiB), gibibyte (GiB) e tebibyte (TiB) sejam usados para se referir às unidades baseadas em potências de 2, enquanto os nomes tradicionais sejam usados apenas para se referir às unidades baseadas em potências de 10, mas os novos termos ainda não se popularizaram.

[.center%autowidth%unbreakable,cols="<,<,<,<",]
|=======================================================================
|Unidade |Tamanho |Bytes |Medida Prática

|byte |8 bits |2^0^ = 10^0^ |um único caracter
|kilobyte (KB) |1,024 bytes |2^10^ &#8776; 10^3^ |um parágrafo de texto
|megabyte (MB) |1,024 kilobytes |2^20^ &#8776; 10^6^ |um minuto de uma música MP3
|gigabyte (GB) |1,024 megabytes |2^30^ &#8776; 10^9^ |uma hora de streaming de vídeo em qualidade padrão
|terabyte (TB) |1,024 gigabytes |2^40^ &#8776; 10^12^|80% da capacidade da memória humana, estimado por Raymond Kurzweil
|=======================================================================

No início desta seção, nos referimos à memória como uma pirâmide. No topo, há uma quantidade pequena, mas muito rápida, de memória. À medida que descemos pela pirâmide, a capacidade de armazenamento aumenta, mas a velocidade diminui. É claro que a pirâmide varia de computador para computador. Abaixo, há uma tabela que mostra vários tipos de memória, ordenados da mais rápida e menor à mais lenta e maior. A velocidade efetiva é difícil de medir (e muda à medida que a tecnologia avança), mas observe que cada camada da pirâmide tende a ser de 10 a 100 vezes mais lenta do que a camada anterior.

[%unbreakable,cols="<15,<25,<60",]
|=======================================================================
|Memória |Capacidade Típica |Uso

|Cache |kilobytes ou megabytes |O cache é um armazenamento rápido e temporário para a própria CPU. As CPUs modernas possuem dois ou três níveis de cache, que se tornam progressivamente maiores e mais lentos.

|RAM |gigabytes |A maior parte da memória primária é a RAM. A RAM vem em módulos que podem ser trocados para atualizar um computador.

|Unidades Flash |gigabytes até terabytes|As unidades flash oferecem um dos armazenamentos secundários mais rápidos disponíveis para consumidores comuns. Os pen drives vêm na forma de dispositivos USB tipo chaveiro, mas também como unidades que ficam dentro do computador (às vezes chamadas de _unidades de estado sólido_ ou SSDs). À medida que o preço das unidades flash caem, espera-se que eles substituam totalmente os discos rígidos. Alguns SSDs já têm capacidades na faixa dos terabytes.

|Discos rígidos |terabytes|Os discos rígidos ainda são o armazenamento secundário mais comum para desktops, laptops e servidores. Eles têm velocidade limitada, em parte devido às suas peças móveis. 

|Backup em fita |terabytes e mais |Algumas grandes empresas ainda armazenam enormes quantidades de informação em fitas magnéticas. As fitas têm bom desempenho para acessos sequenciais longos.

|Armazenamento em rede |terabytes e mais |O armazenamento acessado por meio de uma rede é limitado pela velocidade da rede. Muitas empresas utilizam computadores em rede para backup e redundância, bem como para computação distribuída. Amazon, Google, Microsoft e outras empresas alugam seus sistemas de armazenamento em rede a taxas baseadas no tamanho do armazenamento e na taxa de transferência total de dados. Esses serviços fazem parte do que é chamado de _computação em nuvem_.
|=======================================================================

===== Dispositivos E/S

Os dispositivos de E/S apresentam uma variedade muito maior do que as CPUs ou a memória. Alguns dispositivos de E/S, como as portas USB, estão permanentemente conectados à CPU por meio de uma placa de circuito impresso. Outros dispositivos, chamados de periféricos, são conectados ao computador conforme necessário. Seus tipos e recursos são muitos e variados, e este livro não aborda em profundidade como interagir com dispositivos de E/S.

Dispositivos de entrada comuns incluem mouses, teclados, touchpads, microfones, controles de videogame e mesas digitalizadoras. Dispositivos de saída comuns incluem monitores, alto-falantes e impressoras. Alguns dispositivos realizam tanto entrada quanto saída, como as placas de rede.

Lembre-se de que nossa visão do hardware do computador como CPU, memória e dispositivos de E/S é apenas um modelo. Um soquete PCI Express pode ser considerado um dispositivo de E/S, mas a placa de vídeo que se encaixa no soquete também pode ser considerada um. E o monitor que se conecta à placa de vídeo é mais um. Embora a placa de vídeo seja um dispositivo de E/S, ela também possui seu próprio processador e memória. Não faz sentido se perder em detalhes, a menos que sejam relevantes para o problema que você está tentando resolver. Uma das habilidades mais importantes na ciência da computação é encontrar o nível certo de detalhe e abstração para analisar um determinado problema.

==== Software

Sem hardware, os computadores não existiriam, mas o software é igualmente importante. O software consiste nos programas e dados que são executados e armazenados pelo computador. O foco deste livro é aprender a escrever software.

O software abrange uma variedade quase infinita de programas de computador. Com as ferramentas certas (muitas das quais são gratuitas), qualquer pessoa pode escrever um programa que rode em uma máquina Windows, Mac ou Linux. Embora seja quase impossível listar todos os diferentes tipos de software, vale a pena mencionar algumas categorias.

[horizontal]
Sistemas Operacionais:::
O _sistema operacional_ (SO) é o software que gerencia a interação entre o hardware e o restante do software. Programas chamados _drivers_ são adicionados ao SO para cada dispositivo de hardware. Por exemplo, quando um aplicativo deseja imprimir um documento, ele se comunica com a impressora por meio de um driver de impressora personalizado para aquela impressora específica, o SO e o hardware do computador. O SO também agenda, executa e gerencia a memória para todos os outros programas. Os três SO mais comuns para computadores desktop são o Microsoft Windows, o Apple macOS e o Linux. Atualmente, todos os três rodam em hardware semelhante, baseado nas arquiteturas Intel x86 e x64.
+
A Microsoft não vende computadores desktop, mas muitos computadores desktop e laptops vêm com o Windows pré-instalado. Para pessoas físicas e jurídicas que montam seu próprio hardware, também é possível adquirir o Windows separadamente. Em contrapartida, quase todos os computadores que rodam o macOS são vendidos pela Apple, e o macOS geralmente vem integrado ao computador. O Linux é um _software de código aberto_, o que significa que todo o código-fonte usado para criá-lo está disponível gratuitamente. Apesar do Linux ser gratuito, muitos consumidores preferem o Windows ou o macOS devido à facilidade de uso, compatibilidade com softwares específicos e suporte técnico. Muitos consumidores também não sabem que o hardware pode ser adquirido separadamente de um sistema operacional ou que o Linux é uma alternativa gratuita aos outros dois.
+
Outros computadores também possuem sistemas operacionais. Muitos tipos de telefones celulares utilizam o sistema operacional Android, do Google. O iPad e o iPhone da Apple utilizam o iOS, concorrente da Apple. Telefones, fornos de micro-ondas, automóveis e inúmeros outros dispositivos possuem computadores internos que utilizam algum tipo de sistema operacional incorporado.
+
Considere dois aplicativos em execução em um telefone celular com uma CPU de núcleo único. Um aplicativo é um navegador da web e o outro é um reprodutor de música. O usuário pode começar a ouvir música e, em seguida, iniciar o navegador. Para funcionar, ambos os aplicativos precisam acessar a CPU ao mesmo tempo. Como a CPU tem apenas um núcleo, ela pode executar apenas uma instrução por vez.
+
Em vez de forçar o usuário a terminar de ouvir a música antes de usar o navegador da web, o sistema operacional alterna a CPU entre os dois aplicativos muito rapidamente. Essa alternância permite que o usuário continue navegando enquanto a música toca em segundo plano. O usuário tem a ilusão de que ambos os aplicativos estão usando a CPU ao mesmo tempo.
Compiladores:::
Um _compilador_ é um tipo de programa particularmente importante para os programadores. Os programas de computador são escritos em linguagens especiais, como Java, que são legíveis para os humanos. Um compilador pega esse programa legível para humanos e o transforma em instruções (geralmente código de máquina) que um computador pode entender.
+
Para compilar os programas deste livro, você usa o compilador Java `javac`, seja diretamente, digitando seu nome como um comando, seja indiretamente, por meio do IntelliJ IDEA, Eclipse ou de alguma outra ferramenta que execute o compilador para você.
Aplicativos Empresariais:::
Existem muitos tipos diferentes de programas que se enquadram na categoria de software empresarial ou de produtividade. Talvez o mais conhecido seja o pacote de ferramentas Microsoft Office, que inclui o processador de texto Word, a planilha eletrônica Excel e o software de apresentações PowerPoint.
+
Os programas dessa categoria costumam ser os primeiros a vir à mente quando as pessoas pensam em software, e essa categoria teve um impacto histórico tremendo. A popularidade do Microsoft Office levou à ampla adoção do Microsoft Windows na década de 1990. Um único aplicativo tão desejável que um consumidor está disposto a comprar o hardware e o sistema operacional apenas para poder executá-lo é, às vezes, chamado de _killer app_.
Video Games:::
Os videogames são softwares como qualquer outro programa, mas merecem atenção especial por representarem uma indústria gigantesca, avaliada em bilhões de dólares. Geralmente, são desafiadores de programar, e o setor de desenvolvimento de videogames é altamente competitivo.
+
Os gráficos 3D intensos exigidos pelos videogames modernos levaram fabricantes de hardware como Nvidia, AMD e Intel a desenvolver placas de vídeo de alto desempenho para computadores desktop e laptops. Ao mesmo tempo, empresas como Nintendo, Sony e Microsoft desenvolveram consoles como o Switch 2, o PlayStation 5 e o Xbox Series X, que são especializados em videogames, mas não foram projetados para tarefas gerais de computação.
Navegadores Web:::
Os navegadores da Web são programas capazes de se conectar à Internet, baixar e exibir páginas da Web e outros arquivos. Os primeiros navegadores da Web só conseguiam exibir páginas relativamente simples, contendo texto e imagens. Devido à crescente importância da comunicação pela Internet, os navegadores da Web evoluíram para reproduzir sons, exibir vídeos e permitir uma comunicação sofisticada em tempo real.
+
Entre os navegadores da Web mais populares estão o Microsoft Edge, o Mozilla Firefox, o Apple Safari e o Google Chrome. Cada um deles apresenta vantagens e desvantagens em termos de compatibilidade, conformidade com padrões, segurança, velocidade e suporte ao cliente.

=== Sintaxe: Representação de dados

Após cada seção *Conceitos*, este livro geralmente apresenta uma seção *Sintaxe*. Sintaxe é o conjunto de regras de uma linguagem. Essas seções *Sintaxe* geralmentese concentram em recursos concretos da linguagem Java e em detalhes técnicos relacionados aos conceitos descritos no capítulo.

Neste capítulo, ainda estamos tentando descrever computadores em um nível geral. Consequentemente, os detalhes técnicos que abordaremos nesta seção não serão sobre a sintaxe do Java. Embora tudo o que dizemos se aplique ao Java, também se aplica a muitas outras linguagens de programação.

=== Compiladores e Interpretadores

Este livro trata principalmente da resolução de problemas por meio de programas de computador. Daqui em diante, só mencionaremos o hardware quando ele tiver impacto na programação. O primeiro passo para escrever um programa de computador é decidir qual linguagem usar.

A maioria das pessoas se comunica por meio de línguas naturais, como o chinês, o inglês, o francês, o russo ou o tâmil. No entanto, os computadores têm dificuldade em compreender línguas naturais. Como um meio-termo, os programadores escrevem programas (instruções para o computador seguir) em uma linguagem mais semelhante a uma linguagem natural do que à linguagem compreendida pela CPU. Essas linguagens são chamadas de _linguagens de alto nível_, porque estão mais próximas da linguagem natural (o nível mais alto) do que da _linguagem de máquina_ (o nível mais baixo). Também podemos nos referir à linguagem de máquina como _código de máquina_ ou _código nativo_.

Milhares de linguagens de programação foram criadas ao longo dos anos, mas algumas das linguagens de alto nível mais populares de todos os tempos incluem Fortran, Cobol, Visual Basic, C, {cpp}, Python, Java, JavaScript (que é quase totalmente independente do Java) e C#. 

Como mencionamos na seção anterior, um compilador é um programa que traduz uma linguagem para outra. Em muitos casos, um compilador traduz uma linguagem de alto nível para uma linguagem de baixo nível que a CPU possa compreender e executar. Como todo o trabalho é feito antecipadamente, esse tipo de compilação é conhecido como compilação estática ou antecipada. Em outros casos, a saída do compilador é uma linguagem intermediária que é mais fácil para o computador compreender do que a linguagem de alto nível, mas ainda assim requer alguma tradução antes que o computador possa seguir as instruções.

Um _interpretador_ é um programa semelhante a um compilador. No entanto, um interpretador recebe código em uma linguagem como entrada e, em tempo real, executa cada instrução na CPU à medida que a traduz. Os interpretadores geralmente executam o código mais lentamente do que se ele tivesse sido traduzido para linguagem de máquina antes da execução.

Observe que tanto compiladores quanto interpretadores são programas normais. Eles geralmente são escritos em linguagens de alto nível e compilados para linguagem de máquina antes da execução. Isso levanta uma questão filosófica: se você precisa de um compilador para criar um programa, de onde veio o primeiro compilador?

.(a) Compilação Estática. (b) Execução Interpretada. (c) Compilação em bytecode seguida de compilação just-in-time.
image::compilerFigure.svg[scaledwidth=100%,pdfwidth=100%,width=100%]

.Compilação Java 
====
Java é a popular linguagem de programação de alto nível em que nos concentramos neste livro. A maneira padrão de executar um programa Java envolve uma etapa adicional que muitas linguagens compiladas não possuem. A maioria dos compiladores de Java, embora não todos, traduz um programa escrito em Java para uma linguagem intermediária conhecida como _bytecode_. Essa versão intermediária do programa de alto nível é usada como entrada para outro programa chamado JVM "Java Virtual Machine"(Máquina Virtual Java) . A maioria das JVMs populares traduz o bytecode em código de máquina que é executado diretamente pela CPU. Essa conversão de bytecode em código de máquina é feita com um compilador just-in-time (JIT). É chamado de “just-in-time” porque as seções do bytecode não são compiladas até o momento em que são necessárias. Como a saída será usada para essa execução específica do programa, o JIT pode fazer otimizações para que o código de máquina final funcione particularmente bem no ambiente atual.

Por que o Java usa a etapa intermediária do bytecode? Um dos objetivos de design do Java é ser independente de plataforma, o que significa que ele pode ser executado em qualquer tipo de computador. Esse é um objetivo difícil, pois cada combinação de SO e CPU precisará de instruções de baixo nível diferentes.

O Java aborda o problema mantendo seu bytecode independente de plataforma. Você pode compilar um programa em bytecode em uma máquina Windows e, em seguida, executar o bytecode em uma JVM em um ambiente macOS. Parte do trabalho é independente de plataforma, e parte não é. Cada JVM deve ser adaptada à combinação de sistema operacional e hardware em que é executada. A Sun Microsystems, Inc., desenvolvedora original da linguagem Java e da JVM, comercializou esse recurso da linguagem com o slogan “Escreva uma vez, execute em qualquer lugar.” 

A Sun Microsystems foi comprada pela Oracle Corporation em 2009. A Oracle continua a produzir o HotSpot, a JVM padrão, mas existem muitas outras JVMs, incluindo o Apache Harmony e o Dalvik, a JVM do Google Android.
====

==== Números

Todos os dados dentro de um computador são representados por números. Embora os seres humanos utilizem números em nosso dia a dia, a representação e a manipulação de números pelos computadores funcionam de maneira diferente. Nesta subseção, apresentamos os conceitos de sistemas numéricos, bases, conversão de uma base para outra e aritmética em sistemas numéricos arbitrários.

===== Alguns Sistemas Numéricos

Um sistema numérico é uma forma de representar números. É fácil confundir o _algarismo_ que representa o _número_ com o próprio número. Você pode pensar no número dez como “`10,`”, um algarismo composto por dois símbolos, mas o próprio número é o conceito de *ser dez*. Você poderia expressar essa quantidade levantando todos os dedos, com o símbolo “`X,`” ou batendo dez vezes.

Representar dez com “`10`” é um exemplo de um _sistema numérico posicional_, ou seja, de base 1. Em um sistema numérico posicional, a posição dos dígitos determina a magnitude que eles representam. Por exemplo, o numeral 3.432 contém o dígito 3 duas vezes. Na primeira vez, ele representa três grupos de mil. Na segunda vez, representa três grupos de dez. Em contrapartida, o sistema numérico romano é um exemplo de sistema numérico que *não* é posicional.

O número 3.432 e, possivelmente, todos os outros números escritos normalmente que você já viu são expressos na base 10 ou no sistema _decimal_. É chamado de base 10 porque, à medida que você se move do dígito mais à direita para a esquerda, o valor de cada posição aumenta em um fator de 10. Além disso, na base 10, dez é o menor inteiro positivo que requer dois dígitos para ser representado. Cada número menor tem seu próprio dígito: 0, 1, 2, 3, 4, 5, 6, 7, 8 e 9. Representar dez requer a combinação de dois dígitos existentes. Toda base tem a propriedade de que o número que lhe dá nome requer dois dígitos para ser escrito, a saber, “`1`” e “`0.`” (Uma exceção é a base 1, que não se comporta como as outras bases e não é um sistema numérico posicional normal.)

.Decimal numbers
====
O número 723 pode ser escrito como 723 = 7 · 10^2^ + 2 · 10^1^ + 3 · 10^0^.

Observe que o dígito mais à direita é a casa das unidades, o que equivale a 10^0^. Certifique-se de começar com _b_^0^ e não com _b_^1^_ ao considerar o valor de um número escrito na base _b_, independentemente do valor de _b_. O segundo dígito a partir da direita é multiplicado por 10^1^, e assim por diante. O produto de um dígito pela potência correspondente de 10 nos diz quanto um dígito contribui para o número. Na expansão acima, o dígito 7 contribui com 700 para o número 723. Os dígitos 2 e 3 contribuem, respectivamente, com 20 e 3 para 723.

À medida que avançamos para a direita, a potência de 10 diminui em um, e esse padrão funciona mesmo para potências negativas de 10. Se expandirmos o valor fracionário 0,324, obtemos 0,324 = 3 · 10^-1^ + 2 · 10^-2^ + 4 · 10^-3^.

Podemos combinar os dois números acima para obter 723,324 = 7 · 10^2^ + 2 · 10^1^ + 3 · 10^0^ + 3 · 10^-1^ + 2 · 10^-2^ + 4 · 10^-3^.
====

Podemos estender essas ideias a qualquer base, verificando nossa lógica em relação à conhecida base 10. Suponhamos que um numeral seja composto por _n_ símbolos  _s_~_n_-1~, _s_~_n_-2~, …, _s_~1~, _s_~0~_. Além disso, suponhamos que esse numeral pertença ao sistema numérico de base _b_. Podemos expandir o valor desse numeral da seguinte forma:

[.text-center]
_s_~_n_-1~ _s_~_n_-2~ … _s_~1~ _s_~0~ = _s_~_n_-1~ · _b_^_n_-1^ + _s_~_n_-2~ · _b_^_n_-2^ + … + _s_~1~ · _b_^1^ + _s_~0~ · _b_^0^

O símbolo mais à esquerda no número é o _dígito de maior ordem_ e o símbolo mais à direita é o _dígito de menor ordem_. Por exemplo, no número decimal 492, 4 é o dígito de maior ordem e 2, o dígito de menor ordem.

As frações podem ser expandidas de maneira semelhante. Por exemplo, uma fração com _n_ símbolos _s_~1~, _s_~2~, …, _s_~_n_-1~, _s_~_n_~_ em um sistema numérico de base _b_ pode ser expandida para:

[.text-center]
0._s_~1~ _s_~2~ … _s_~_n_-2~ _s_~_n_-1~ = _s_~1~ · _b_^-1^ + _s_~2~ · _b_^-2^ + … + _s_^_n_-1^ · _b_^-_n_+1^ + _s_~_n_~ · _b_^-_n_^

Como cientistas da computação, temos um interesse especial pela base 2, pois é a base usada para expressar números dentro dos computadores. A base 2 também é chamada de _binária_. Os únicos símbolos permitidos para representar números em binário são “`0`” e “`1`”, os dígitos binários ou _bits_.

No número binário 10011, o 1 mais à esquerda é o bit de ordem mais alta e o 0 mais à direita é o bit de ordem mais baixa. Pelas regras dos sistemas numéricos posicionais, o bit de ordem mais alta representa 1 · 2^4^ = 16.

.Números binários
====
Exemplos de números escritos em binário são 100~2~, 111~2~, 10101~2~ e 11000001~2~ Lembre-se de que a base do sistema numérico binário é 2. Assim, podemos escrever um número em binário como a soma dos produtos das potências de 2. Por exemplo, o número 10011~2~ pode ser expandido para:

[.text-center]
10011~2~ = 1 · 2^4^ + 0 · 2^3^ + 0 · 2^2^ + 1 · 2^1^ + 1 · 2^0^ = 16 + 0 + 0 + 2 + 1 = 19

Ao expandir o número, também mostramos como converter um número binário em um número decimal. Lembre-se de que tanto 10011~2~ quanto 19 representam o mesmo valor, ou seja, dezenove. A conversão entre bases altera apenas a forma como o número é escrito. Como antes, o bit mais à direita é multiplicado por 2^0^ para determinar sua contribuição para o número binário. O bit à sua esquerda é multiplicado por 2^1^ para determinar sua contribuição, e assim por diante. Neste caso, o 1 mais à esquerda contribui com 1 · 2^4^ = 16 para o valor.
====

****
<<binaryParityExercise>> +
<<positiveBinaryToDecimalExercise>>
****

Outro sistema numérico útil é o _base 16_, também conhecido como _hexadecimal_. O sistema hexadecimal é surpreendente porque requer mais do que os 10 dígitos a que estamos acostumados. Os números nesse sistema são escritos com 16 dígitos hexadecimais, que incluem os dez dígitos de 0 a 9 e as seis letras A, B, C, D, E e F. As seis letras, começando por A, correspondem aos valores 10, 11, 12, 13, 14 e 15.

O hexadecimal é usado como uma representação compacta do binário. Embora os números binários possam ficar muito longos, quatro dígitos binários podem ser representados com apenas um único dígito hexadecimal.

.Números hexadecimais
====
39A~16~, 32~16~ e AFBC12~16~ são exemplos de números escritos em hexadecimal. Um número hexadecimal pode ser expresso como a soma dos produtos das potências de 16. Por exemplo, o número hexadecimal A0BF~16~ pode ser expandido para:

[.text-center]
A · 16^3^ + 0 · 16^2^ + B · 16^1^ + F ·
16^0^

Para converter um número hexadecimal em decimal, devemos substituir os dígitos de A a F pelos valores de 10 a 15. Agora podemos reescrever a soma dos produtos acima como:

[.text-center]
10 · 16^3^ + 0 · 16^2^ + 11 · 16^1^ + 15 · 16^0^ = 40.960 + 0 + 176 + 15 = 41.151

Assim, obtemos A0BF~16~ = 41.151.
====

O sistema numérico de base 8 também é chamado de _octal_. Assim como o hexadecimal, o octal é usado como uma forma abreviada do binário. Um número octal utiliza os dígitos octais 0, 1, 2, 3, 4, 5, 6 e 7. Fora isso, aplicam-se as mesmas regras. Por exemplo, o número octal 377 pode ser expandido para:

[.text-center]
377~8~ = 3 · 8^2^ + 7 · 8^1^ + 7 · 8^0^ = 255

Você deve ter notado que nem sempre fica claro em qual base um numeral está escrito. A sequência de dígitos 337 é um numeral válido em octal, decimal e hexadecimal, mas representa números diferentes em cada sistema. Os matemáticos usam um subscrito para indicar a base na qual um numeral está escrito.

Assim, 337~8~ = 255~10~, 377~10~ = 377~10~, e 377~16~ = 887~10~. Os números de base são sempre escritos na base 10. Presume-se que um número sem subscrito esteja na base 10. Em Java, não há como marcar subscritos, então são usados prefixos. O prefixo `0b` é usado para binário, o prefixo `0` é usado para octal, nenhum prefixo é usado para decimal e o prefixo `0x` é usado para hexadecimal. Os números correspondentes no código Java seriam, portanto, escritos como `0377`, `377` e `0x377`. Tenha cuidado para não preencher números com zeros em Java, pois eles podem ser interpretados como base 8! Lembre-se de que o valor `056` *não* é o mesmo que o valor `56` em Java.

A tabela a seguir lista algumas características dos quatro sistemas numéricos que discutimos, com representações dos números 7 e 29.

[.center%autowidth%unbreakable%header,cols="<.^,^.^,<.^,<.^,<.^",]
|=======================================================================
<.^|Sistema Numérico
^.^|Base
<.^|Digitos
<.^|Numerais +
Matemáticos
<.^|Numerais +
Java
|Binário |2 |0, 1 |111~2~, 11101~2~ | `0b111`, `0b11101`
|Octal |8 |0, 1, 2, 3, 4, 5, 6, 7 |7~8~, 35~8~|`07`, `035`
|Decimal |10 |0, 1, 2, 3, 4, 5, 6, 7, 8, 9 |7, 29|`7`, `29`
|Hexadecimal |16 |0, 1, 2, 3, 4, 5, 6, 7, 8, 9, A, B, C, D, E, F|7~16~, 1D~16~ |`0x7`,`0x1D`
|=======================================================================

===== Conversão entre sistemas numéricos

É útil saber como converter um número representado em uma base para a representação equivalente em outra base. Nossos exemplos mostraram como converter um número em qualquer base para o sistema decimal, expandindo-o na forma de soma de produtos e, em seguida, somando os diferentes termos. Mas como converter um número decimal para outra base?

===== Conversão decimal para binário

Existem pelo menos duas maneiras diferentes de converter um número decimal em binário. Uma delas consiste em escrever o número decimal como uma soma de potências de dois, como na seguinte conversão do número 23.

[.text-center]
23 = 16 + 0 + 4 + 2 + 1 = 1 · 2^4^ + 0 · 2^3^ + 1 · 2^2^ + 1 · 2^1^ + 1 · 2^0^ = 10111~2~

Primeiro, encontre a maior potência de dois que seja menor ou igual ao número. Neste caso, 16 se encaixa, pois 32 é muito grande. Subtraia esse valor do número, restando 7 neste caso. Em seguida, repita o processo. O último passo é reunir os coeficientes das potências de dois em uma sequência para obter o equivalente binário. Usamos 16, 4, 2 e 1, mas pulamos o 8. Se escrevermos um 1 para cada posição que usamos e um 0 para cada posição que pulamos, obtemos 2³ = 10111~2~. Embora esse seja um procedimento simples para a conversão de decimal para binário, ele pode ser complicado para números maiores.

****
<<positiveDecimalToBinaryExercise>>
****

Uma maneira alternativa de converter um número decimal em seu equivalente binário é dividir o número dado por 2 até que o quociente seja 0 (mantendo apenas a parte inteira do quociente). A cada etapa, registre o resto obtido ao dividir por 2. Reúna esses restos (que serão sempre 0 ou 1) para formar o equivalente binário. O bit menos significativo é o resto obtido após a primeira divisão, e o bit mais significativo é o resto obtido após a última divisão. Em outras palavras, essa abordagem determina os dígitos do número binário na ordem inversa.

.Conversão decimal para binário com resto
====
Vamos usar esse método para converter 23 em seu equivalente binário. A tabela a seguir mostra as etapas necessárias para a conversão. A coluna mais à esquerda indica o número da etapa. A segunda coluna contém o número a ser dividido por 2 em cada etapa. A terceira coluna contém o quociente de cada etapa, e a última coluna contém o resto atual.

[.center%autowidth%unbreakable,cols="^,>,>,>",]
|=========================================
|Etapa |Número |Quociente |Resto

|1 |23 |11 |1
|2 |11 |5 |1
|3 |5 |2 |1
|4 |2 |1 |0
|5 |1 |0 |1
|=========================================

Começamos dividindo 23 por 2, obtendo 11 como quociente e 1 como resto. O quociente 11 é então dividido por 2, resultando em 5 como quociente e 1 como resto. Esse processo continua até chegarmos a um quociente de 0 e um resto de 1 na Etapa 5. Agora escrevemos os restos do mais recente para o menos recente e obtemos o mesmo resultado de antes, 23 = 10111~2~.
====

===== Outras conversões

Um número decimal pode ser convertido para seu equivalente hexadecimal usando qualquer um dos dois procedimentos descritos acima. Em vez de escrever um número decimal como uma soma de potências de 2, escreve-se como uma soma de potências de 16. Da mesma forma, ao usar o método da divisão, em vez de dividir por 2, divide-se por 16. A conversão para o sistema octal é semelhante.

****
<<convertDecimalToOctalAndHexExercise>>
****

Usamos o sistema hexadecimal porque é fácil converter dele para o binário e vice-versa. A tabela a seguir lista os equivalentes binários dos 16 dígitos hexadecimais.

[.center%autowidth%unbreakable%header,cols="^.>,^.>,^,^.>,^.>",]
|==============================================================
|Dígito +
Hexadecimal
|Equivalente +
Binário
|
|Dígito +
Hexadecimal
|Equivalente +
Binário

|0 |0000  | |8 |1000
|1 |0001  | |9 |1001
|2 |0010  | |A |1010
|3 |0011  | |B |1011
|4 |0100  | |C |1100
|5 |0101  | |D |1101
|6 |0110  | |E |1110
|7 |0111  | |F |1111
|==============================================================

Com a ajuda da tabela acima, vamos converter 3FA~16~ para binário. Por simples substituição, 3FA~16~ = 0011 1111 1010~2~. Observe que agrupamos os dígitos binários em blocos de 4 bits cada. É claro que os zeros mais à esquerda no equivalente binário são irrelevantes, pois não contribuem para o valor do número.

****
<<octalEquivalentsOfBinaryExercise>> +
<<convertOctalToBinaryExercise>>
****

===== Representação de números inteiros em um computador

Na matemática, os números binários podem representar números arbitrariamente grandes. Dentro de um computador, o tamanho de um número é limitado pelo número de bits usados para representá-lo. Para cálculos de uso geral, são comumente utilizados inteiros de 32 e 64 bits. O maior inteiro que o Java representa com 32 bits é 2.147.483.647, o que é suficiente para a maioria das tarefas. Para números maiores, o Java pode representar até 9.223.372.036.854.775.807 com 64 bits. O Java também oferece representações para inteiros usando 8 e 16 bits.

Essas representações são fáceis de determinar para números positivos: encontre o equivalente binário do número e, em seguida, preencha o lado esquerdo com zeros para ocupar o espaço restante. Por exemplo, 19 = 10011~2~. Se armazenado usando 8 bits, 19 seria representado como `0001 0011`. Se armazenado usando 16 bits, 19 seria representado como `0000 0000 0001 0011`. (Separamos grupos de 4 bits para facilitar a leitura).

===== Aritmética binária

Lembre-se de que os computadores lidam com números em sua representação binária, o que significa que toda a aritmética é realizada com números binários. Às vezes, é útil compreender como esse processo funciona e compará-lo com a aritmética decimal. A tabela abaixo lista as regras para a adição binária. +

[.center%autowidth%unbreakable,cols="^h,>,>"]
|========
|+ |0 |1

|0 |0 |1
|1 |1 |10
|========

Conforme indicado acima, a soma de dois 1s resulta em um 0, com um transporte de 1 para a posição seguinte à esquerda. A soma de números compostos por mais de um bit segue as mesmas regras de qualquer soma, transportando valores excessivamente grandes para a posição seguinte. Na soma decimal, valores acima de 9 devem ser transportados. Na soma binária, valores acima de 1 devem ser transportados. O exemplo a seguir mostra uma demonstração de soma binária. Para simplificar a apresentação, assumimos que os números inteiros são representados com apenas 8 bits.

.Adição binária
====
Vamos somar os números 60 e 6 no sistema binário. Usando as técnicas de conversão descritas acima, podemos ver que 60 = 111100₂ e 6 = 110₂. No computador, esses números já estariam no sistema binário e preenchidos com zeros à esquerda para ocupar 8 bits. +

[.center%autowidth%unbreakable,cols="^,>,>",]
|=====================
| |Binário |Decimal

| m|0011 1100 m|60
|+ m|0000 0110 m|6
| m|0100 0010 m|66
|=====================

O resultado não é nenhuma surpresa, mas observe que a soma pode ser realizada em binário sem a necessidade de conversão para decimal em nenhum momento.
====

A subtração no sistema binário também é semelhante à subtração no sistema decimal. As regras estão apresentadas na tabela a seguir.

[.center%autowidth%unbreakable,cols="^h,>,>"]
|==========
|- |0 |1

|0 |0 |1
|1 |(1)1 |0
|==========

Ao subtrair um 1 de um 0, toma-se emprestado um 1 da posição imediatamente à esquerda. O exemplo a seguir ilustra a subtração binária.

.Subtração binária
====
Mais uma vez, usaremos 60 e 6 e seus equivalentes binários indicados acima.

[.center%autowidth%unbreakable,cols="^,>,>",]
|=====================
| |Binário |Decimal

| m|0011 1100 m|60
|- m|0000 0110 m|6
| m|0011 0110 m|54
|=====================
====

****
<<hexArithmeticExercise>>
****

===== Representação de números inteiros negativos em um computador

Os números inteiros negativos também são representados na memória do computador como números binários, utilizando um sistema chamado _complemento a dois_. Ao analisar a representação binária de um número inteiro com sinal em um computador, o bit mais à esquerda (o mais significativo) será 1 se o número for negativo e 0 se for positivo. Infelizmente, encontrar a representação de um número negativo envolve mais do que apenas inverter esse bit.

Suponhamos que precisemos encontrar o equivalente binário do número decimal -12 usando 8 bits na forma de complemento de dois. O primeiro passo é converter 12 para seu equivalente binário de 8 bits. Ao fazer isso, obtemos 12 = `0000 1100`. Observe que o bit mais à esquerda da representação é um 0, indicando que o número é positivo. Em seguida, calculamos o complemento a dois da representação de 8 bits em duas etapas. Na primeira etapa, invertemos todos os bits, ou seja, mudamos todos os 0 para 1 e todos os 1 para 0. Isso nos dá o _complemento a um_ do número, `1111 0011`. Na segunda etapa, somamos 1 ao complemento a um para obter o complemento a dois. O resultado é `1111 0011` + `1` = `1111 0100`. 

Assim, o equivalente binário de 8 bits em complemento de dois de -12 é `1111 0100`. Observe que o bit mais à esquerda é um 1, indicando que este é um número negativo.

****
<<onesToTwosComplementProcessExercise>> +
<<onesToTwosComplementExercise>>
****

.De decimal para complemento a dois
====
Vamos converter -29 para seu equivalente binário, assumindo que o número será armazenado na forma de complemento a dois de 8 bits. Primeiro, convertemos o número positivo 29 para seu equivalente binário de 8 bits: 29 = `0001 1101`.

Em seguida, obtemos o complemento à 1 da representação binária invertendo os 0s para 1s e os 1s para 0s. Isso nos dá `1110 0010`. Por fim, somamos 1 à representação do complemento à 1 para obter `1110 0010` + `1` = `1110 0011`, que é o equivalente binário desejado de -29.
====

****
<<convertNegativeDecimalToBinaryExercise>>
****

.Complemento de dois para decimal
====
Vamos converter o valor de 8 bits em complemento de dois `1000 1100` para decimal. Observamos que o bit mais à esquerda desse número é 1, o que o torna um número negativo. Portanto, invertemos o processo de formação do complemento de dois. Primeiro, subtraímos 1 da representação, obtendo `1000 1100` - `1` = `1000 1011`. Em seguida, invertemos todos os bits nesta forma de complemento de um, obtendo `0111 0100`.

Convertemos essa representação binária em seu equivalente decimal, obtendo 116. Assim, o equivalente decimal de `1000 1100` é -116.
====

****
<<convertNegativeBinaryToDecimalExercise>>
****

Por que os computadores usam o complemento a dois? Em primeiro lugar, eles precisam de um sistema capaz de representar tanto números positivos quanto negativos. Eles poderiam ter usado o bit mais à esquerda como bit de sinal e representado o restante do número como um número binário positivo. Fazer isso exigiria uma verificação desse bit e alguma conversão para números negativos toda vez que o computador quisesse realizar uma adição ou subtração.

Devido à forma como foi projetado, os números inteiros positivos e negativos armazenados no complemento a dois podem ser somados ou subtraídos *sem* nenhuma conversão especial. O bit mais à esquerda é somado ou subtraído exatamente como qualquer outro bit, e os valores que ultrapassam o bit mais à esquerda são ignorados. O complemento a dois tem uma vantagem sobre o complemento de um, pois existe apenas uma representação para o zero. O próximo exemplo mostra o complemento a dois em ação.

.Aritmética do complemento a dois
====
Vamos somar -126 e 126. Após realizar as conversões necessárias, suas representações em complemento de dois de 8 bits são `1000 0010` e `0111 1110`.

[.center%autowidth%unbreakable,cols="^,>,>",]
|=====================
| |Binário |Decimal

| m|1000 0010 m|-126
|+ m|0111 1110 m|126
| m|0000 0000 m|0
|=====================

Como experado, a soma retorna 0.

Agora, vamos somar os dois números inteiros negativos -126 e -2, cujas representações em complemento de dois de 8 bits são `1000 0010` e `1111 1110`.

[.center%autowidth%unbreakable,cols="^,>,>",]
|=====================
| |Binário |Decimal

| m|1000 0010 m|-126
|+ m|1111 1110 m|-2
| m|1000 0000 m|-128
|=====================

O resultado é -128, que é o menor número inteiro negativo que pode ser representado no complemento a dois de 8 bits.
====

****
<<binaryArithmeticExercise>>
****

===== Estouro e estouro negativo

Ao realizar operações aritméticas com números, diz-se que ocorre um estouro quando o resultado da operação é maior do que o maior valor que pode ser armazenado nessa representação. Diz-se que ocorre um estouro negativo quando o resultado da operação é menor do que o menor valor possível.

Tanto os estouros quanto os estouros negativos levam a valores que retornam ao início do intervalo. Por exemplo, somar dois números positivos pode resultar em um número negativo, ou somar dois números negativos pode resultar em um número positivo.

.Adição binária com estouro
====
Vamos somar os números 124 e 6. Suas representações em complemento de dois, de 8 bits, são `0111 1100` e `0000 0110`.

[.center%autowidth%unbreakable,cols="^,>,>"]
|=====================
| |Binário |Decimal

| m|0111 1100 m|124
|+ m|0000 0110 m|6
| m|1000 0010 m|-126
|=====================

Esse resultado surpreendente ocorre porque o maior inteiro de 8 bits no complemento a dois é 127. A soma de 124 e 6 resulta em 130, um valor superior a esse máximo, o que causa um estouro com um resultado negativo.
====

O menor número (o mais negativo) que pode ser representado no complemento a dois de 8 bits é -128. Um resultado menor que esse resultará em um estouro negativo. Por exemplo, -115 - 31 = 110. Experimente as conversões necessárias para testar esse resultado.

===== Bitwise operators

Although we most commonly manipulate numbers using traditional
mathematical operations such as addition, subtraction, multiplication,
and division, there are also operations that work directly on the binary
representations of the numbers. Some of these operators have clear relationships
to mathematical operations, and some don't.

[.center%unbreakable,cols="^.<15,<.<20,<.<65",width=90%]
|=======================================================================
|Operator |Name |Description

| `&`  |Bitwise AND |Combines two binary representations into a new
representation which has a 1 in every position where both the original
representations have a 1

|`\|` |Bitwise OR |Combines two binary representations into a new
representation which has a 1 in every position where either of the
original representations has a 1

| `^` |Bitwise XOR |Combines two binary representations into a new
representation which has a 1 in every position that the original
representations have different values

|`~` |Bitwise complement |Takes a representation and creates a new
representation in which every bit is flipped from 0 to 1 and 1 to 0

| `<<` |Signed left shift |Moves all the bits the specified number of
positions to the left, shifting 0s into the rightmost bits

| `>>` |Signed right shift |Moves all the bits the specified number of
positions to the right, padding the left with copies of the sign bit

| `>>>` |Unsigned right shift |Moves all the bits the specified number of
positions to the right, padding with 0s
|=======================================================================

Bitwise AND, bitwise OR, and bitwise XOR take two integer
representations and combine them to make a new representation. In
bitwise AND, each bit in the result will be a 1 if *both* of the
original integer representations in that position are 1 and 0 otherwise.
In bitwise OR, each bit in the result will be a 1 if *either* of the
original integer representations in that position are 1 and 0 otherwise.
In bitwise XOR, each bit in the result will be a 1 if the two bits of
the original integer representations in that position are *different*
and 0 otherwise.

Bitwise complement is a unary operator like the negation operator (`-`).
Instead of merely changing the sign of a value (which it will also do),
its result changes every 1 in the original representation to 0 and
every 0 to 1.

The signed left shift, signed right shift, and unsigned right shift
operators all create a new binary representation by shifting the bits in
the original representation a certain number of places to the left or
the right. The signed left shift moves the bits to the left, padding
with 0s. If you do a signed left shift
by _n_ positions, it's equivalent to multiplying the number
by 2^_n_^ (until overflow occurs). The signed right shift moves the bits to the
right, padding with whatever the sign bit is. If you do a signed right
shift by _n_ positions, it's equivalent to dividing the
number by 2^_n_^ (with integer division). The unsigned right
shift moves the bits to the right, including the sign bit, filling the
left side with 0s. An unsigned right shift will always make a value
positive but is otherwise similar to a signed right shift. A few
examples follow.

.Bitwise operators
====
Here are a few examples of the result of bitwise operations. We'll
assume that the values are represented using 32-bit two's complement,
instead of using 8-bit values as before. In Java, bitwise operators
automatically convert smaller values to 32-bit representations before
proceeding.

Let's consider the result of `21 & 27`.

[.center%autowidth%unbreakable,cols="^,>,>",]
|==================================================
| |Binary |Decimal

| |`0000 0000 0000 0000 0000 0000 0001 0101` |21
|`&` |`0000 0000 0000 0000 0000 0000 0001 1011` |27
| |`0000 0000 0000 0000 0000 0000 0001 0001` |17
|==================================================

Note how this result is different from `21 | 27`.

[.center%autowidth%unbreakable,cols="^,>,>",]
|==================================================
| |Binary |Decimal

| |`0000 0000 0000 0000 0000 0000 0001 0101` |21
|`\|` |`0000 0000 0000 0000 0000 0000 0001 1011` |27
| |`0001 1111` |31
|==================================================

And also from `21 ^ 27`.

[.center%autowidth%unbreakable,cols="^,>,>",]
|=================================================
| |Binary |Decimal

| |`0000 0000 0000 0000 0000 0000 0001 0101` |21
|`^` |`0000 0000 0000 0000 0000 0000 0001 1011` |27
| |`0000 1110` |14
|=================================================

Ignoring overflow, signed left shifting is equivalent to repeated
multiplications by 2. Consider `11 << 3`. The representation
`0000 0000 0000 0000 0000 0000 0000 1011` is shifted to the left to make
`0000 0000 0000 0000 0000 0000 0101 1000` = 88 = 11 · 2^3^.

Signed right shifting is equivalent to repeated integer divisions by 2.
Consider `-104 >> 2`. The representation
`1111 1111 1111 1111 1111 1111 1001 1000` is shifted to the right to
make `1111 1111 1111 1111 1111 1111 1110 0110` = -26 = -104 ÷ 2^2^.

Unsigned right shifting is the same as signed right shifting except when
it is done on negative numbers. Since their sign bit is replaced by `0`,
an unsigned right shift produces a (generally large) positive number.
Consider `-104 >>> 2`. The representation
`1111 1111 1111 1111 1111 1111 1001 1000` is shifted to the right to
make `0011 1111 1111 1111 1111 1111 1110 0110` = 1,073,741,798.

Because of the way two's complement is designed, bitwise complement is
equivalent to negating the sign of the number and then subtracting
1. Consider `~(-104)`. The
representation `1111 1111 1111 1111 1111 1111 1001 1000` is complemented
to `0000 0000 0000 0000 0000 0000 0110 0111` = 103.
====

===== Rational numbers

We've seen how to represent positive and negative integers in computer
memory, but this section shows how rational numbers, such as 12.33,
-149.89, and 3.14159, can be converted into binary and represented.

===== Scientific notation

_Scientific notation_ is closely related to the way a computer
represents a rational number in memory. Scientific notation is a tool
for representing very large or very small numbers without writing a lot
of zeroes. A decimal number in scientific notation is written
_a_ × 10^_b_^ where _a_ is called the
_mantissa_ and _b_ is called the _exponent_.

For example, the number 3.14159 can be written in scientific notation as
0.314159 × 10^1^. In this case, 0.314159
is the mantissa, and 1 is the exponent. Here a few more
examples of writing numbers in scientific notation.

[.center%autowidth,grid="none", frame="none",cols=">,^,<"]
|===
|3.14159|=|3.14159 × 10^0^
|3.14159|=|314159 × 10^-5^
|-141.324|=|-0.141324 × 10^3^
|30,000|=|.3 × 10^5^
|===


There are many ways of writing any given number in scientific notation. A more
standardized way of writing real numbers is _normalized scientific
notation_. In this notation, the mantissa is always written as a number
whose absolute value is less than 10 but greater than or equal to 1.
Following are a few examples of decimal numbers in normalized scientific
notation.

[.center%autowidth,grid="none", frame="none",cols=">,^,<"]
|===
|3.14159|=|3.14159 × 10^0^
|-141.324|=|-1.41324 × 10^2^
|30,000|=|3.0 × 10^4^
|===

A shorthand for scientific notation is E notation, which is written with
the mantissa followed by the letter '`E`' followed by the exponent. For
example, 39.2 in E notation can be written 3.92E1 or 0.392E2. The letter '`E`' should be read
"`multiplied by 10 to the power.`" It's legal to use E notation to represent
numbers in scientific notation in Java.

===== Fractions

A rational number can be broken into an integer part and a fractional
part. In the number 3.14, 3 is the integer part, and .14 is the
fractional part. We've already seen how to convert the integer part to
binary. Now, we'll see how to convert the fractional part into binary.
We can then combine the binary equivalents of the integer and fractional
parts to find the binary equivalent of a decimal real number.

A decimal fraction _f_ is converted to its binary equivalent
by successively multiplying it by 2. At the end of each multiplication
step, either a 0 or a 1 is obtained as an integer part and is recorded
separately. The remaining fraction is again multiplied by 2 and the
resulting integer part recorded. This process continues until the
fraction reduces to zero or enough binary digits for the desired
precision have been found. The binary equivalent of _f_ then
consists of the bits in the order they have been recorded, as shown in
the next example.

.Fraction conversion to binary
====
Let's convert 0.8125 to binary. The table below shows the steps to do
so.

[.center%unbreakable,cols=">10,>20,>20,>25,>25",width=60%]
|=======================================================================
|Step |_f_ |2__f__ |Integer part |Remainder

|1 |0.8125 |1.625 |1 |0.625

|2 |0.625 |1.25 |1 |0.25

|3 |0.25 |0.5 |0 |0.5

|4 |0.5 |1.0 |1 |0
|=======================================================================

We then collect all the integer parts and get 0.1101~2~ as the binary
equivalent of 0.8125. We can convert this binary fraction back into
decimal to verify that it's correct.

[.text-center]
0.1101~2~ = 1 · 2^-1^ + 1 · 2^-2^ + 0 · 2^-3^ + 1 · 2^-4^ = 0.5 + 0.25 + 0 + 0.0625 = 0.8125
====

In some cases the process described above will never have a remainder
of 0.  Then, we can only find an approximate representation of
the given fraction as demonstrated in the next example.

.Non-terminating fraction
[[Non-terminating_fraction]]
====
Let's convert 0.3 to binary assuming that we have only five bits in
which to represent the fraction. The following table shows the five
steps in the conversion process. +

[.center%unbreakable,cols=">10,>20,>20,>25,>25",width=60%]
|=======================================================================
|Step |_f_ |2__f__ |Integer part |Remainder

|1 |0.3 |0.6 |0 |0.6

|2 |0.6 |1.2 |1 |0.2

|3 |0.2 |0.4 |0 |0.4

|4 |0.4 |0.8 |0 |0.8

|5 |0.8 |1.6 |1 |0.6
|=======================================================================

Collecting the integer parts we get 0.01001~2~ as the binary representation
of 0.3. Let's convert this back to decimal to see how accurate it is.

[.text-center]
0.01001~2~ = 0 · 2^-1^ + 1 · 2^-2^ + 0 · 2^-3^ + 0 · 2^-4^ + 1 · 2^-5^ = 0 + 0.25 + 0 + 0 + 0.03125 = 0.28125

Five bits are not enough to represent 0.3 fully. Indeed, perfect accuracy would require
an infinite number of bits! In this case, we have
an error of 0.3 - 0.28125 = 0.01875. Most computers use many
more bits to represent fractions and obtain much better accuracy in
their representation.
====

****
<<baseConversionErrorExercise>> +
<<terminatingDecimalExercise>>
****

Now that we understand how integers as well as fractions can be
converted from one number base to another, we can convert any rational
number from one base to another. The next example demonstrates one such
conversion.

.Rational number converted to binary
====
Let's convert 14.3 to binary assuming that we'll only use six bits to
represent the fractional part. First we convert 14 to binary using the
technique described earlier. This gives us 14 = 1110~2~.
Taking the method outlined in <<Non-terminating_fraction>> one step further, our six bit
representation of 0.3 is 0.010011~2~. Combining the two representations
gives 14.3 = 1110.010011~2~.
====

===== Floating-point representation

_Floating-point representation_ is a system used to represent rational numbers
in computer memory. In this notation a number is represented as
_a_ × _b_^_e_^, where _a_ gives the
_significant digits_ (mantissa) of the number and _e_ is the
exponent. The system is very similar to scientific notation, but
computers usually use base _b_ = 2 instead of
10.

For example, we could write the binary number 1010.1~2~ in floating-point
representation as 10.101~2~ × 2^2^ or as
101.01~2~ × 2^1^. In any case, this number is equivalent to
10.5 in decimal.

In standardized floating-point representation, _a_ is written so
that only the most significant non-zero digit is to the left of the
decimal point. Most computers use the IEEE 754 floating-point representation
to represent rational numbers. In this notation, the memory to store the
number is divided into three segments: one bit used to mark the sign of
the number, _m_ bits to represent the mantissa (also known
as the _significand_), and _e_ bits to represent the
exponent.

In IEEE floating-point representation, numbers are commonly represented using
32 bits (known as _single precision_) or using 64 bits (known as _double
precision_). In single precision, _m_ = 23 and
_e_ = 8. In double precision, _m_ = 52 and
_e_ = 11. To represent positive and negative exponents, the
exponent has a _bias_ added to it so that the result is never negative.
This bias is 127 for single precision and 1,023 for double precision.
The packing of the sign bit, the exponent, and the mantissa is shown in
<<numberRepresentationFigure>> (a) and (b).

.Single precision IEEE format
====
The following is a step-by-step demonstration of how to construct the
single precision binary representation in IEEE format of the number
10.5.

[start]
.  Convert 10.5 to its binary equivalent using methods described
earlier, yielding 10.5~10~ = 1010.1~2~. Unlike the case
of integers, the sign of the number is taken care of separately for
floating-point. Thus, we would use 1010.1~2~ for
-10.5 as well.
.  Write this binary number in standardized floating-point representation,
yielding 1.0101~2~ × 2^3^.
.  Remove the leading bit (always a 1 for non-zero numbers), leaving `0101`.
.  Pad the fraction with zeroes on the right to fill the 23-bit
mantissa, yielding `0101 0000 0000 0000 0000 000`. Note that the decimal
point is ignored in this step.
.  Add 127 to the exponent. This gives us an exponent of
3 + 127 = 130.
.  Convert the exponent to its 8-bit unsigned binary equivalent. Doing
so gives us 130~10~ = 10000010~2~.
.  Set the sign bit to 0 if the number is positive and to 1 otherwise.
Since 10.5 is positive, we set the sign bit to 0.

We now have the three components of 10.5 in binary. The memory
representation of 10.5 is shown in <<numberRepresentationFigure>> (c).
Note in the figure how the sign bit, the exponent, and the mantissa are
packed into 32 bits.
====

****
<<floatingPointBinaryExercise>>
****

[[numberRepresentationFigure]]
.Layouts for floating-point representation (a) in single precision, (b) in double precision, and (c) of 10.5~10~ in single precision.
image::numberRepresentationFigure.svg[scaledwidth=100%,pdfwidth=100%,width=100%]

===== Largest and smallest numbers

Fixing the number of bits used for representing a real number limits the
numbers that can be represented in computer memory using the floating-point
notation. The largest rational number that can be represented in
single precision has an exponent of 127 (254 after bias) with a mantissa
consisting of all 1s: +
`0 1111 1110 1111 1111 1111 1111 1111 111` +
This number is approximately 3.402 × 10^38^. To
represent the smallest (closest to zero) non-zero number, we need to
examine one more complication in the IEEE format. An exponent of 0
implies that the number is unnormalized. In this case, we no longer
assume that there is a 1 bit to the left of the mantissa. Thus, the
smallest non-zero single precision number has its exponent set to 0 and
its mantissa set to all zeros with a 1 in its
23^rd^ bit: +
`0 0000 0000 0000 0000 0000 0000 0000 001` +
Unnormalized single precision values are considered to have an exponent
of -126. Thus, the value of this number is
2^-23^ × 2^-126^ =
2^-149^ ≈ 1.4 × 10^-45^. Now that we know the rules for
storing both integers and floating-point numbers, we can list the
largest and smallest values possible in 32- and 64-bit representations
in Java in the following table. Note that *largest* means the
largest positive number for both integers and floating-point values, but
*smallest* means the most negative number for integers and the smallest
positive non-zero value for floating-point values. +

[.center%autowidth%unbreakable,cols="<,<,<",]
|=======================================================================
|Format |Largest number |Smallest number

|32-bit integer |2,147,483,647
|-2,147,483,648

|64-bit integer |9,223,372,036,854,775,807
|-9,223,372,036,854,775,808

|32-bit floating-point |3.4028235 × 10^38^
|1.4 × 10^-45^

|64-bit floating-point |1.7976931348623157 × 10^308^
|4.9^-324^
|=======================================================================

Using the same number of bits, floating-point representation can store
much larger numbers than integer representation. However, floating-point
numbers are not always exact, resulting in approximate results when
performing arithmetic. Always use integer formats when fractional parts
aren't needed.

===== Special numbers

Several binary representations in the floating-point representation correspond
to special numbers. These numbers are reserved and do not have the values that
would be expected from normal multiplication of the mantissa by the power of 2
given by the exponent.

0.0 and -0.0:::
  When the exponent and the mantissa are both 0, the number is
  interpreted as a 0.0 or -0.0 depending on the sign bit. For example,
  in a Java program, dividing 0.0 by -1.0 results in -0.0. Similarly,
  -0.0 divided by -1.0 is 0.0. Positive and negative zeroes only exist
  for floating-point values. -0 is the same as 0 for integers. Dividing
  the integer 0 by -1 in Java results in 0 and not in -0.
Positive and negative infinity:::
  An overflow or an underflow might occur while performing arithmetic on
  floating-point values. In the case of an overflow, the resulting
  number is a special value that Java recognizes as infinity. In the
  case of an underflow, it is a special negative infinity value. For
  example, dividing 1.0 by 0.0 in Java results in infinity and dividing
  -1.0 by 0.0 results in negative infinity. These values have well
  defined behavior. For example, adding 1.0 to infinity yields infinity. +
  Note that floating-point values and integers do not behave in the same
  way. Dividing the integer 1 by the integer 0 creates an error that can
  crash a Java program.
Not-a-number (`NaN`):::
  Some mathematical operations may result in an undefined number. For
  example, the square root of a negative number is an imaginary number. Java has a
  value set aside for results that are not rational numbers. When we
  discuss how to find the square root of a value in Java, this
  not-a-number value will be the answer for the square root of a
  negative number.

===== Errors in floating-point arithmetic

As we have seen, many rational numbers can only be approximately
represented in computer memory. Thus, arithmetic done on the approximate
values yields approximate answers. For example, 1.3 cannot be
represented exactly using a 64-bit value. In this case, the product
`1.3 * 3.0` will be `3.9000000000000004` instead of `3.9`. This error will propagate as
additional operations are performed on previous results. The next
example illustrates this propagation of errors when a sequence of
floating-point operations are performed.

.Error propagation
====
Suppose that the price of several products is added to determine
the total price of a purchase at a cash register that uses floating-point arithmetic with a 32-bit variable (the equivalent of a `float` in Java).
For simplicity, let's assume that all items have a
price of $1.99. We don't know how many items will be purchased ahead of
time and simply add the price of each item until all items have been
scanned at the register. The table below shows the value of the total
cost for different quantities of items.

[.center%autowidth%unbreakable,cols=">,>,>,>,>",]
|=======================================================================
|Items |Correct Cost |Calculated Cost |Absolute Error |Relative Error

|100 |199.0 |1.9900015E02 |1.5258789E-04 |7.6677333E-07

|500 |995.0 |9.9499670E02 |3.2958984E-03 |3.3124606E-06

|1000 |1990.0 |1.9899918E03 |8.1787109E-03 |4.1099051E-06

|10000 |19900.0 |1.9901842E04 |1.8417969E00 |9.2552604E-05
|=======================================================================

The first column in the table above is the number of items. The second
column is the correct cost of all items purchased. The third column is
the cost calculated by adding each item using single precision
floating-point addition. The fourth and fifth columns give the absolute and
relative errors, respectively, of the calculated value. Note how the
error increases as the number of additions goes up. In the last row, the
absolute error is almost two dollars.
====

While the above example may seem unrealistic, it does expose the
inherent dangers of floating-point calculations. Although the error is
less when using double precision representations, it still exists.

=== Solução: Comprando um computador

We pose a motivating problem in the *Problem* section near the beginning
of most chapters. Whenever there is a *Problem* section, there is a
*Solution* section near the end in which we give a solution to the earlier
problem.

After all the discussion of the hardware, software, and data
representation inside of a computer, you might feel more confused about
which computer to buy than before. As a programmer, it's important to
understand how data is represented, but this information plays virtually
no role in deciding which computer to buy. Unlike most problems in this
book, there's no concrete answer we can give here. Because the
development of technology progresses so rapidly, any advice about
computer hardware or software has a short shelf-life.

Software is a huge consideration, beginning with the OS. Because the
choice of OS usually affects choice of hardware, we'll start there. The
three major choices for a desktop or laptop OS are Microsoft Windows,
Apple macOS, and Linux.

Windows is heavily marketed for business use.
Windows used to suffer from many stability and security issues,
but Microsoft has worked hard to address these. Apple macOS and the
computers it's installed on are marketed to an artistic and
counter-culture population. Linux is popular among tech savvy users.
Putting marketing biases aside, the three operating systems have become
more similar over time, and most people could be
productive using any of the three. The following table lists some pros
and cons for each OS.

[.center%unbreakable,cols="<20h,<40,<40",]
|=======================================================================
|OS |Pros |Cons

|Microsoft Windows
a|
[.text-left]
* Compatible with the largest number of programs
* Can be purchased separately from hardware

a|
[.text-left]
* Expensive
* Security concerns

|Apple macOS
a|
[.text-left]
* Polished user interface
* Bundled with many useful programs
* Tested for use on the hardware it comes with

a|
[.text-left]
* Most expensive
* Many business applications and games are released late or not at all for macOS
* Difficult to run on non-Apple hardware

|Linux
a|
[.text-left]
* Free
* Runs on almost any hardware
* Highly customizable
* Served by a community that develops many free applications for it

a|
[.text-left]
* Can be difficult to install or configure
* Few commercial applications are available for it
* Limited customer support

|=======================================================================

Once you've decided on an OS, you can pick hardware and other software
that's compatible with it. For macOS, almost all your hardware choices
will be computers sold by Apple. For Windows and Linux, you can either
have a computer built for you or build your own. Although computer
hardware changes quickly, let's examine some general guidelines.

CPU::
Remember that the speed of a CPU is measured in GHz (billions of clock
cycles per second). Higher GHz is generally better, but it's hard to
compare performance across different designs of CPU. There's also a
diminishing returns effect: The very fastest, very newest CPUs are
often considerably more expensive even if they only provide slightly
better performance. It's usually more cost effective to select a CPU
in the middle of the performance spectrum.
+
Cache size also has a huge effect on performance. The larger the
cache, the less often the CPU has to read data from slower
memory. Since most new CPUs available today are 64-bit, the question
of word size is no longer significant.

Memory::
Memory includes RAM, hard drives, optical drives, and any other
storage. RAM is usually easy to upgrade for desktop machines and less
easy (though often possible) for laptops. It takes a little bit of research to
get exactly the right kind of RAM for your CPU and motherboard, and the amount
of RAM is dependent on what you want to do with your system. The
minimum amount of RAM to run Microsoft Windows 11 is 4 GB.
The recommended amount of RAM to
run Apple macOS Sequoia is at least 8 GB. A good guideline is to have
at least twice the minimum required RAM.
+
Hard drive space is dependent on how you expect to use your
computer. 1 TB and 2 TB drives are not very expensive, and either
represents a huge amount of storage. Only if you plan to have enormous
libraries of video or uncompressed audio data will you likely need
more. Corporate-level databases and web servers and some other
business systems can also require vast amounts of space. Hard drive
speed is greatly affected by the hard drive's cache size. As always, a
bigger cache means better performance. Using a solid state drive (SSD)
instead of a traditional hard drive has much better performance and has become
standard on most new desktops and laptops.
+
Installing optical drives and other storage devices depends on
individual needs. With the rise of streaming services and cloud backup,
optical drives have almost disappeared.
I/O Devices::
The subject of I/O devices is personal. It's difficult to say
what anyone should buy without considering his or her specific needs.
A monitor is the essential visual output device while a keyboard and
mouse are the essential input devices. Speakers are important as
well. Most laptops have all these elements integrated in one form or
another. Laptops often have inexpensive web cameras installed as well.
+
Someone interested in video games might want to invest in a powerful
graphics card. Newer cards with more video RAM are generally better
than older cards with less, but which card is best at a given price
point is the subject of continual discussion at sites like
https://www.tomshardware.com[Tom's Hardware^].
+
Printers are still useful output devices. Graphics tablets can make it
easier to create digital art on a computer. The number of potentially
worthwhile I/O devices is limitless.

This section is a jumping off point for purchasing a computer. As
you learn more about computer hardware and software, it will become
easier to know what combination of the two will serve your needs. Of
course, there's always more to know, and technology changes quickly.

==== Concurrency: Multicore processors

Over the last two decades, the word "`core`" has been splattered all over CPU
packaging. Intel in particular has marketed the idea heavily with its
older Core and Core 2 models and its modern Core i3, Core i5, Core i7,
and Core i9 chips. What are all these cores?

Looking back into the past, most consumer processors had a single
_core_, or brain. They could only execute one instruction at a time.
Even this definition is hazy, because pipelining kept more
than one instruction in the process of being executed, but overall
execution proceeded sequentially.

The advent of multicore processors changed this design
significantly. Each processor now has several independent cores, each of
which can execute different instructions at the same time. Before the
arrival of multicore processors, a few desktop computers and many
supercomputers had multiple separate processors that could achieve a
similar effect. However, since multicore processors have more than one
effective processor on the same silicon die, the communication time
between processors is much faster and the overall cost of a
multi-processor system is cheaper.

===== The Good

Multicore systems have impressive performance. The first multicore
processors had two cores, but current designs have four, six, eight,
or higher. A processor with eight cores can
execute eight different programs at the same time. Or, when faced with a
computationally intense problem like matrix math, code breaking, or
scientific simulation, a processor with eight cores could solve the
problem eight times as fast. A desktop processor with 100 cores that can
solve a problem 100 times faster is not out of reach.

In fact, modern graphics cards are already blazing this trail. Consider
the 1080p standard for high definition video, which has a resolution of
1,920 × 1,080 _pixels_. Each pixel (short for _picture element_) is a dot on the screen.
A screen whose resolution is 1080p has
2,073,600 dots. To maintain the illusion of smooth movement, these dots
should be updated around 30 times per second. Computing the color for
more than 2 million dots based on 3D geometry, lighting, and physics
effects 30 times a second is no easy feat, and many video game enthusiasts
demand a frame rate of 60 times a second or higher. Some of the cards used to
render computer games have hundreds or thousands of cores. These cores
are not general purpose or completely independent. Instead, they're
specialized to do certain kinds of matrix transformations and
floating-point computations.

Nevertheless, the power of these graphics cards has fueled recent improvements
in AI. Even though the cores are not general purpose, skilled hardware and
software engineers have found ways to harness their incredible parallel
computation to solve difficult problems. Writing code that takes advantage of
these architectures is challenging, but servers filled with the fastest graphics
cards are used for everything from mining cryptocurrencies to training large
language models. The company Nvidia alone sells tens of billions of dollars
worth of graphics cards every year.

****
<<multicoreChipExercise>>
****

===== The Bad

Although chip-makers have spent a lot of money marketing multicore
technology, they haven't spent much money explaining that one of the
driving forces behind the "`multicore revolution`" was a simple failure
to make processors faster in other ways. In 1965, Gordon Moore, one of
the founders of Intel, remarked that the density of silicon
microprocessors had been doubling every year (though he later revised
this to every two years), meaning that twice as many transistors
(computational building blocks) could fit in the same physical space.
This trend, often called Moore's Law, held up reasonably well through the
twentieth century. For years, clever designs relying on shorter communication
times, pipelining, and other schemes succeeded in doubling the effective
performance of processors every two years.

At some point, the tricks became less effective and exponential gains in
processor clock rate could no longer be sustained. As clock frequency
increases, the signal becomes more chaotic, and it becomes more
difficult to tell the difference between the voltages that represent 0s
and 1s. Another problem is heat. The energy that a processor uses is
related to the *square* of the clock rate. This relationship means that
increasing the clock rate of a processor by a factor of four will increase
its energy consumption (and heat generation) by a factor of 16.

The legacy of Moore's Law lives on. We're still able to fit more and
more transistors into tinier and tinier spaces. After decades of
increasing clock rate, chip-makers began using the additional silicon
density to make processors with more than one core instead. Since 2005
or so, increases in clock rate have stagnated.

===== The Ugly

Does a processor with eight cores solve problems eight times as fast as
its single core equivalent? Unfortunately, the answer is "`Almost
never.`" Most problems are not easy to break into eight independent
pieces.

For example, if you want to build eight houses and you have eight
construction teams, then you probably can get pretty close to completing
all eight houses in the time it would have taken for one team to build a
single house. But what if you have eight teams and only one house to
build? You might be able to finish the house a little early, but some
steps necessarily come after others: The concrete foundation must be
poured and solid before framing can begin. Framing must be finished
before the roof can be put on. And so on.

Like building a house, most problems you can solve on a computer are
difficult to break into concurrent tasks. A few problems are like
painting a house and can be completed much faster with lots of
concurrent workers. Other tasks simply cannot be done faster with more
than one team on the job. Worse, some jobs can actually interfere with
each other. If a team is trying to frame the walls while another team is
trying to put the roof onto unfinished walls, neither will succeed, the
house might be ruined, and people could get hurt.

On a desktop computer, individual cores generally have their own level 1
cache but share level 2 cache and RAM. If the programmer isn't careful,
he or she can give instructions to the cores that will make them fight
with each other, overwriting memory that other cores are using and
crashing the program or giving an incorrect answer. Imagine
if different parts of your brain were completely independent and fought
with one another. The words coming out of your mouth might be gibberish.

To recap, the first problem with concurrent programming is finding ways
to break down problems so that they can be solved faster with multiple
cores. The second problem is making sure that the different cores
cooperate so that the answer is correct and makes sense. These are not
easy problems, and researchers are still working on finding better
ways to do both.

Some educators believe that beginners will be confused by concurrency
and should wait until later courses to confront these problems. We
disagree: Forewarned is forearmed. Concurrency is an integral part of
modern computation, and the earlier you get introduced to it, the more
familiar it'll be.

=== Resumo

This introductory chapter focused on the fundamentals of a computer. We
began with a description of computer hardware, including the CPU,
memory, and I/O devices. We also described the software of a computer,
highlighting key programs such as the operating system and compilers as
well as other useful programs like business applications, video games,
and web browsers.

Then, we introduced the topic of how numbers are represented inside the
computer. Various number systems and conversion from one system to
another were explained. We discussed how floating-point representation is used
to represent rational numbers. A sound knowledge of data representation
helps a programmer decide what kind of data to use (integer or
floating-point and how much precision) as well as what kind of errors to expect
(overflow, underflow, and floating-point precision errors).

The next chapter extends the idea of data representation into the
specific types of data that Java uses and introduces representation
systems for individual characters and text.

=== Exercícios

*Conceptual Problems*

. Name a few programming languages other than Java.

. What's the difference between machine code and bytecode?

. What are some advantages of JIT compilation over traditional,
ahead-of-time compilation?

. [[binaryParityExercise]] Without converting to decimal, how can one find out whether a given
binary number is odd or even?

. [[positiveBinaryToDecimalExercise]] Convert the following positive binary numbers into decimal.
[loweralpha]
.. 100~2~
.. 111~2~
.. 100000~2~
.. 111101~2~
.. 10101~2~

. [[positiveDecimalToBinaryExercise]] Convert the following positive decimal numbers into binary.
[loweralpha]
..  1
..  15
..  100
..  1,025
..  567,899

. [[onesToTwosComplementProcessExercise]] What's the process for converting the representation of a binary
integer given in one's complement into two's complement?

. [[onesToTwosComplementExercise]] Perform the conversion from one's complement to two's complement on the
representation `1011 0111`, which uses 8 bits for storage.

. [[convertDecimalToOctalAndHexExercise]] Convert the following decimal numbers to their hexadecimal and octal
equivalents.
[loweralpha]
..  29
..  100
..  255
..  382
..  4,096

. [[octalEquivalentsOfBinaryExercise]] Create a table that lists the binary equivalents of octal digits, similar to the one in <<Other conversions>>. Hint: Each octal digit can be represented as a sequence of three binary digits.

. [[convertOctalToBinaryExercise]] Use the table from <<octalEquivalentsOfBinaryExercise>> to convert the following octal numbers to binary.
[loweralpha]
..  337~8~
..  24~8~
..  777~8~

. The ternary number system has a base of 3 and uses symbols 0, 1, and 2
to construct numbers. Convert the following decimal numbers to their ternary equivalents.
[loweralpha]
..  23
..  333
..  729

. [[convertNegativeDecimalToBinaryExercise]] Convert the following decimal numbers to 8-bit, two's complement binary
representations.
[loweralpha]
..  -15
..  -101
..  -120

. [[convertNegativeBinaryToDecimalExercise]] Given the following 8-bit binary representations in two's complement,
find their decimal equivalents.
[loweralpha]
..  `1100 0000`
..  `1111 1111`
..  `1000 0001`

. [[binaryArithmeticExercise]] Perform the following arithmetic operation on the following 8-bit, two's
complement binary representations of integers. Check your answers by
performing arithmetic on equivalent decimal numbers.
[loweralpha]
..  `0000 0011` + `0111 1110` =
..  `1000 1110` + `0000 1111` =
..  `1111 1111` + `1000 0000` =
..  `0000 1111` - `0001 1110` =
..  `1000 0001` - `1111 1100` =

. [[hexArithmeticExercise]] Extrapolate the rules for decimal and binary addition to rules for the
hexadecimal system. Then, use these rules to perform the following
additions in hexadecimal. Check your answers by converting the values
and their sums to decimal.
[loweralpha]
..  A2F~16~ + BB~16~ =
..  32C~16~ + D11F~16~ =

. [[baseConversionErrorExercise]] Expand <<Non-terminating_fraction>> assuming that you have ten bits to represent the
fraction. Convert the representation back to base 10. How far off is
this value from 0.3?

. [[terminatingDecimalExercise]] Will the process in <<Non-terminating_fraction>> ever terminate, assuming that we can use as
many bits as needed to represent 0.3 in binary? Why or why not?

. [[floatingPointBinaryExercise]] Derive the binary representation of the following decimal numbers
assuming 32-bit (single) precision representation using the IEEE 754
floating-point format.
[loweralpha]
..  0.0125
..  7.7
..  -10.3

. The IEEE 754 standard also defines a 16-bit (half) precision format. In
this format there is one sign bit, five bits for the exponent, and ten
bits for the mantissa. This format is the same as single and double
precision in that it assumes that a bit with a value of 1 precedes the
ten bits in the mantissa. It also uses a bias of 15 for the exponent.
What's the largest decimal number that can be stored in this format?

. Let _a_, _b_, and _c_ denote three real numbers.
With real numbers, each of the equations below is true. Now suppose that
all arithmetic operations are performed using floating-point
representations of these numbers. Indicate which of the following
equations are still always true and which are sometimes false.
[loweralpha]
..  (_a_ + _b_) + _c_ = _a_ + (_b_ + _c_)
..  _a_ + _b_ = _b_ + _a_
..  _a_ · _b_ = _b_ · _a_
..  _a_ + 0 = _a_
..  (_a_ · _b_) · _c_ = _a_ · (_b_ · _c_)
..  _a_ · (_b_ + _c_) = (_a_ · _b_) + (_a_ · _c_)

. [[multicoreChipExercise]] What's a multicore microprocessor? Why do you think a multicore chip
might be better than a single core chip? Search the Internet to find
the specifications for a few common multicore chips. Which chip does your computer
use?
