[#selection]
:imagesdir: chapters/selection/images
:programsdir: chapters/selection/programs
== SeleĂ§ĂŁo

[quote, Albert Camus]
____
A vida Ă© a soma de todas as suas escolhas.
____

=== Problema: SimulaĂ§ĂŁo de Monty Hall

Existe um famoso enigma matemĂĄtico chamado problema de Monty Hall,
baseado no programa de televisĂŁo _Let's Make a Deal_, apresentado pelo homĂŽnimo
Monty Hall. Neste problema, sĂŁo apresentadas trĂȘs portas. Duas das
trĂȘs portas escondem lixo. Uma porta selecionada aleatoriamente
esconde algo como uma pilha de ouro. Se vocĂȘ conseguir escolher essa porta, vocĂȘ
ganha o ouro. Depois que vocĂȘ faz uma escolha inicial, Monty, que sabe atrĂĄs de qual
porta estĂĄ a pilha de ouro, abrirĂĄ uma das duas outras portas,
sempre escolhendo uma porta com lixo atrĂĄs dela. Se vocĂȘ escolheu a porta do ouro,
Monty escolherĂĄ aleatoriamente entre as duas portas com lixo. Depois de abrir uma
porta, Monty lhe dĂĄ a chance de trocar para a outra porta fechada. VocĂȘ
decide trocar ou nĂŁo, a porta apropriada Ă© aberta e vocĂȘ ganha
ou lixo ou uma pilha de ouro, dependendo da sua sorte.

Acontece que Ă© sempre uma estratĂ©gia melhor trocar de porta. Se vocĂȘ
mantiver sua escolha inicial, tem 1 em 3 de chance de ganhar o ouro.
No entanto, se vocĂȘ trocar de porta, terĂĄ 2 em 3 de chance. O problema Ă©
contraintuitivo e leva muitas pessoas, incluindo matemĂĄticos e
pessoas com pĂłs-graduaĂ§ĂŁo, Ă  resposta incorreta.

Pense da seguinte maneira: suponha que vocĂȘ possa escolher duas portas para abrir e
que, se o ouro estiver atrĂĄs de qualquer uma delas, vocĂȘ ganhe. Claramente, vocĂȘ teria 2
em 3 de chance de ganhar. Monty permite essa opĂ§ĂŁo. Basta escolher as duas
portas que vocĂȘ quiser e dizer a Monty qual Ă© a terceira. Ele revela que uma das suas duas portas iniciais
Ă© lixo, e vocĂȘ troca para a outra.

Se vocĂȘ ainda nĂŁo estĂĄ convencido, tudo bem. Seu objetivo Ă© escrever um
programa que simule o dilema de Monty Hall, permitindo que o usuĂĄrio adivinhe
uma porta e, em seguida, possivelmente troque. Depois de escrever a
simulaĂ§ĂŁo, vocĂȘ pode optar por jogar repetidamente e ver como se sai se
mudar de porta.

Um cenĂĄrio de Monty Hall tem duas caracterĂ­sticas significativas que o distinguem
dos problemas dos capĂ­tulos anteriores. Primeiro, a aleatoriedade desempenha um papel.
A geraĂ§ĂŁo de nĂșmeros aleatĂłrios tornou-se uma parte importante da ciĂȘncia da computaĂ§ĂŁo
, e a maioria das linguagens fornece aos programadores ferramentas para
gerar nĂșmeros aleatĂłrios ou praticamente aleatĂłrios. Lembre-se da classe `Random`
de <<strings-primitive-types#strings-primitive-types>>. Com um objeto de
tipo `Random` chamado `random`, vocĂȘ pode gerar um `int` aleatĂłrio entre
`0` e `n - 1` chamando `random.nextInt(n)`.

A segunda caracterĂ­stica, e muito mais importante, do Java na soluĂ§ĂŁo para
esse problema Ă© o elemento de escolha. Uma porta aleatĂłria Ă© escolhida para esconder
o ouro, e o programa deve reagir adequadamente. O usuĂĄrio escolhe uma porta,
e o programa deve escolher cuidadosamente outra porta para abrir em resposta.
Por fim, o usuĂĄrio deve decidir se deseja ou nĂŁo mudar
sua escolha. Inerente a esse problema estĂĄ a ideia de _execuĂ§ĂŁo condicional_. 
Todos os programas do capĂ­tulo anterior sĂŁo executados sequencialmente,
linha por linha. Com a execuĂ§ĂŁo condicional, apenas parte do cĂłdigo pode ser
executada, dependendo da entrada do usuĂĄrio ou dos valores que os nĂșmeros aleatĂłrios
assumem. Anteriormente, todos os programas eram determinĂ­sticos, uma sĂ©rie de
consequĂȘncias inevitĂĄveis. Agora, esse paradigma linear, em que uma coisa segue a outra,
se dividiu em ĂĄrvores complexas e redes de possĂ­veis execuĂ§Ă”es de programas.

=== Conceitos: Escolhendo entre opĂ§Ă”es

Antes de abordarmos os nĂșmeros aleatĂłrios e as escolhas complexas envolvidas no
problema de Monty Hall, vamos falar sobre a abordagem simplificada que a maioria das
linguagens de programaĂ§ĂŁo adota para a execuĂ§ĂŁo condicional. Quando chegamos a um
ponto em um programa onde hĂĄ uma escolha a ser feita, podemos pensar
nisso como a pergunta: "`Quero realizar esta sĂ©rie de tarefas?`" Assim como
o clĂĄssico jogo das 20 Perguntas, essas perguntas em Java geralmente tĂȘm apenas
duas respostas: "`sim`" ou "`nĂŁo.`" Se a resposta for "`sim`", o
programa conclui a Tarefa A; caso contrĂĄrio, conclui a Tarefa B. Ă mais fĂĄcil
projetar linguagens de programaĂ§ĂŁo que possam lidar com perguntas do tipo sim ou nĂŁo do que
qualquer pergunta geral. Se vocĂȘ jĂĄ estudou lĂłgica no passado, provavelmente se deparou com a 
_lĂłgica booleana_. A lĂłgica booleana fornece um conjunto de regras,
semelhantes Ă s regras da ĂĄlgebra tradicional, que podem ser aplicadas a um
sistema com apenas dois valores: verdadeiro e falso.

==== Escolhas simples

Como queremos construir um sistema usando apenas perguntas do tipo sim ou nĂŁo,
a lĂłgica booleana Ă© perfeita para a ciĂȘncia da computaĂ§ĂŁo. Para nos alinharmos com
outros cientistas da computaĂ§ĂŁo, tentamos pensar nas condiĂ§Ă”es em termos de
verdadeiro e falso, em vez de sim e nĂŁo. Assim, podemos comeĂ§ar a formular
os tipos de escolhas que queremos fazer:

====
_Se estiver chovendo lĂĄ fora,_
=====
_vou levar meu guarda-chuva._
=====
====


Essa afirmaĂ§ĂŁo Ă© um programa muito simples, embora nĂŁo seja um
executado por um computador. A pessoa que segue esse programa se pergunta:
"`EstĂĄ chovendo hoje?`" Se a resposta for "`sim,`", entĂŁo ela vai levar
seu guarda-chuva. Podemos abstrair essa ideia um pouco mais dizendo que
_estĂĄ chovendo lĂĄ fora_ Ă© uma condiĂ§ĂŁo _p_ e que _levar meu
guarda-chuva_ Ă© uma aĂ§ĂŁo _a_. Em outras palavras, se
_p_ for verdadeiro, entĂŁo faĂ§a _a_. NĂŁo especificamos
o que deve ser feito se _p_ nĂŁo for verdadeiro, embora possamos 
supor que o ator nesse drama *nĂŁo* levarĂĄ um guarda-chuva.

Se quisermos ver _p_ como uma decisĂŁo a ser tomada, podemos especificar
o que acontece se nĂŁo for verdade. Por exemplo, poderĂ­amos formular outra
escolha:

====
_Se eu tiver pelo menos R$50 no bolso,_
=====
_vou jantar lagosta;_
=====
_caso contrĂĄrio,_
=====
_vou comer fast food._
=====
====

Nesse caso, vamos considerar _ter pelo menos R$50_ como a condiĂ§ĂŁo _q_,
_jantar lagosta_ como a aĂ§ĂŁo _b_ e _comer fast
food_ como a aĂ§ĂŁo _c_. Agora criamos uma decisĂŁo. Se
_q_ for verdadeiro, a pessoa realizarĂĄ a aĂ§ĂŁo _b_, mas
se for falso, ela realizarĂĄ a aĂ§ĂŁo _c_.

==== OperaĂ§Ă”es booleanas

Por si sĂł, a capacidade de escolher entre duas opĂ§Ă”es jĂĄ Ă© poderosa, mas
podemos ampliar essa capacidade de algumas maneiras. Primeiro, nĂŁo precisamos
depender de condiĂ§Ă”es simples. Usando a lĂłgica booleana, podemos criar condiĂ§Ă”es arbitrariamente complexas.

====
_Se eu estiver entediado, ou se for tarde e eu nĂŁo conseguir dormir,_
=====
_vou assistir televisĂŁo._
=====
====

AlguĂ©m seguindo este programa assistirĂĄ televisĂŁo se estiver entediado ou
se for tarde e tambĂ©m nĂŁo conseguir dormir. Podemos dividir a condiĂ§ĂŁo em
trĂȘs subcondiĂ§Ă”es: _estou entediado_ Ă© a condiĂ§ĂŁo _x_, _Ă©
tarde_ Ă© a condiĂ§ĂŁo _y_, e _nĂŁo consigo dormir_ Ă© a condiĂ§ĂŁo
_z_. Conectamos essas trĂȘs condiĂ§Ă”es usando
as palavras "`e`" e "`ou`". Essas duas palavras simples representam conceitos poderosos
na lĂłgica booleana: *AND* e *OR*. Quando duas condiĂ§Ă”es sĂŁo combinadas
com AND, o resultado Ă© verdadeiro apenas se ambas as condiĂ§Ă”es forem verdadeiras. Quando duas
condiĂ§Ă”es sĂŁo combinadas com OR, o resultado Ă© verdadeiro se qualquer uma das
condiĂ§Ă”es for verdadeira.

Podemos criar uma tabela chamada _tabela verdade_ para mostrar todos os valores possĂ­veis
que certas condiĂ§Ă”es podem assumir. Vamos usar o sĂ­mbolo
â§ para representar o conceito de AND e o sĂ­mbolo
âš para representar o conceito de OR. TambĂ©m vamos
abreviar verdadeiro como T e falso como F.

Dadas uma condiĂ§ĂŁo _x_, uma condiĂ§ĂŁo _y_ e a condiĂ§ĂŁo formada por _x_ â§ _y_,
esta tabela verdade mostra todos os valores possĂ­veis. Conforme estipulado, _x_ â§ _y_ Ă© verdadeiro apenas quando tanto _x_ quanto _y_ sĂŁo verdadeiros.

[.center%autowidth%unbreakable,cols="^,^,^",]
|=========================================================
|_x_ |_y_ |_x_ â§ _y_

|T |T |T
|T |F |F
|F |T |F
|F |F |F
|=========================================================

Esta tabela verdade apresenta todos os valores para _x_ âš _y_. Como vocĂȘ pode ver, _x_ âš _y_ Ă© verdadeiro se _x_ ou _y_ forem verdadeiros.

[.center%autowidth%unbreakable,cols="^,^,^",]
|========================================================
|_x_ |_y_ |_x_ âš _y_

|T |T |T
|T |F |T
|F |T |T
|F |F |F
|========================================================

HĂĄ uma confusĂŁo em torno da palavra "`ou`" em inglĂȘs.
Ăs vezes, "`ou`" Ă© usada em um sentido exclusivo para significar um ou outro
, mas nĂŁo ambos, como em: "`VocĂȘ gostaria de limonada ou chĂĄ gelado com sua
refeiĂ§ĂŁo?`" Na lĂłgica, esse "ou" exclusivo tambĂ©m existe e Ă© chamado de XOR.
Essa diferenĂ§a fornece mais um motivo para que uma linguagem formalmente estruturada
como a matemĂĄtica ou Java nos permita expressar-nos com precisĂŁo. Quando duas
condiĂ§Ă”es sĂŁo conectadas com XOR, o resultado Ă© verdadeiro se uma ou a
outra, mas nĂŁo ambas as condiĂ§Ă”es, forem verdadeiras. Usamos o sĂ­mbolo
â para representar a operaĂ§ĂŁo XOR na tabela verdade
abaixo.

Esta tabela verdade fornece todos os valores para _x_ â _y_.

[.center%autowidth%unbreakable,cols="^,^,^",]
|==========================================================
|_x_ |_y_ |_x_ â _y_

|V |V |F
|V |F |V
|F |V |V
|F |F |F
|==========================================================

As operaĂ§Ă”es AND, OR e XOR sĂŁo todas operaĂ§Ă”es binĂĄrias, como a adiĂ§ĂŁo
e a multiplicaĂ§ĂŁo. Elas conectam duas condiĂ§Ă”es para obter um
resultado. HĂĄ tambĂ©m uma Ășnica operaĂ§ĂŁo unĂĄria na lĂłgica booleana, o operador NOT
. Um NOT simplesmente inverte uma condiĂ§ĂŁo. Se uma condiĂ§ĂŁo for verdadeira,
entĂŁo NOT aplicado a essa condiĂ§ĂŁo resultarĂĄ em falso, e vice-versa.

Aqui estĂĄ uma tabela verdade para NOT, usando o sĂ­mbolo ÂŹ para representar a operaĂ§ĂŁo NOT.

[.center%autowidth%unbreakable,cols="^,^",]
|======================================
|_x_ |ÂŹ__x__

|T |F
|F |T
|======================================

Agora que definimos algumas notaĂ§Ă”es para a lĂłgica booleana, podemos
expressar a expressĂŁo complicada que nos levou a este caminho em
primeiro lugar. Lembre-se de que _x_ Ă© _estou entediado_,
_y_ Ă© _Ă© tarde_ e _z_ Ă© _nĂŁo consigo dormir_.
Seja _d_ a aĂ§ĂŁo _vou assistir televisĂŁo_. Podemos
expressar a escolha desta forma: Se _x_ âš (_y_ â§ _z_),
entĂŁo faĂ§a _d_. Usando essa notaĂ§ĂŁo, expressamos
precisamente as condiĂ§Ă”es para assistir televisĂŁo, usando parĂȘnteses para
esclarecer a ambiguidade presente na afirmaĂ§ĂŁo original. Se pudermos mapear
condiĂ§Ă”es individuais para variĂĄveis booleanas, podemos construir condiĂ§Ă”es de
complexidade arbitrĂĄria.

==== Escolhas aninhadas

Fazer uma escolha Ă© muito bom, mas na vida e nos programas de computador
, podemos ter que fazer muitas escolhas inter-relacionadas. Por exemplo, se
vocĂȘ escolher comer em um restaurante de frutos do mar, entĂŁo poderĂĄ escolher entre
comer camarĂŁo e lagosta, mas se, em vez disso, escolher comer em uma
churrascaria, as opĂ§Ă”es de camarĂŁo e lagosta podem nĂŁo estar disponĂ­veis.

Uma escolha _aninhada_ Ă© aquela que estĂĄ dentro de outra escolha que vocĂȘ
jĂĄ fez. PoderĂ­amos descrever as escolhas de restaurantes e refeiĂ§Ă”es da
seguinte forma.

====
_Se eu quiser frutos do mar,_
=====
_vou comer no Bocas's, onde_
======
_se eu tiver pelo menos US$ 50,_
=======
_vou pedir a lagosta;_
=======
_caso contrĂĄrio,_ 
=======
_vou pedir o camarĂŁo._
=======
======
=====
_Mas se eu nĂŁo quiser frutos do mar,_
=====
_vou comer no Ataliba, onde_
======
_se eu tiver pelo menos $30,_
=======
_vou pedir o filĂ© mignon;_
=======
_caso contrĂĄrio,_ 
=======
_vou pedir as costeletas de porco._
=======
======
=====
====


A descriĂ§ĂŁo anterior Ă© longa, mas expressa com precisĂŁo as
decisĂ”es que nosso comensal imaginĂĄrio poderia tomar. Essa descriĂ§ĂŁo em portuguĂȘs
tem desvantagens: Ă© longa e repetitiva, e o agrupamento de opĂ§Ă”es especĂ­ficas
de refeiĂ§Ă”es com restaurantes especĂ­ficos nĂŁo fica claro.

Na prĂłxima seĂ§ĂŁo, discutiremos a sintaxe Java que nos permite
expressar os mesmos tipos de padrĂ”es de decisĂŁo. Ao contrĂĄrio do portuguĂȘs, Java foi
projetado para tornar essas sequĂȘncias de decisĂ”es claras e fĂĄceis de
ler.

=== Sintaxe: SeleĂ§ĂŁo em Java

Com algumas noĂ§Ă”es teĂłricas sobre os tipos de escolhas que nos
interessam, podemos agora discutir a sintaxe Java usada para
descrever essas escolhas. NĂŁo foi por acaso que repetimos vĂĄrias vezes a
palavra "`if`", pois o principal recurso da linguagem Java para fazer escolhas
Ă© chamado de instruĂ§ĂŁo `if`.

==== InstruĂ§Ă”es `if`

Os criadores do Java estudaram a lĂłgica booleana e criaram um tipo chamado
`boolean`. Toda condiĂ§ĂŁo usada por uma instruĂ§ĂŁo `if` deve ser avaliada como um
valor `boolean`, que sĂł pode ser uma de duas coisas: `true` ou `false`.

Por exemplo, poderĂ­amos ter uma variĂĄvel `boolean` chamada `raining`. Armazenado
nessa variĂĄvel estĂĄ o valor `true` se estiver chovendo e `false` se
nĂŁo estiver. Usando a sintaxe Java, poderĂ­amos codificar nosso primeiro exemplo, no qual nosso
ator pega seu guarda-chuva quando estĂĄ chovendo.

[source,java]
----
if (chovendo) {
    guardaChuva.pegar();
}
----

A aĂ§ĂŁo realizada se estiver chovendo Ă© feita chamando um _mĂ©todo_ em um
_objeto_. Discutiremos objetos e mĂ©todos mais adiante em
<<methods#methods>> e <<classes#classes>>. O que estamos
focando agora Ă© que a linha `guardaChuva.pegar();` Ă© executada *apenas* se
`raining` tiver o valor `true`. Nada Ă© feito se for `false`.
<<figure-if>> mostra esse padrĂŁo de execuĂ§ĂŁo condicional
seguido por todas as instruĂ§Ă”es `if`.

[[figure-if]]
[.text-center]
.A execuĂ§ĂŁo ocorre dentro da instruĂ§ĂŁo `if` quando sua condiĂ§ĂŁo Ă© `true` e a ignora caso contrĂĄrio.
image::if.svg[scaledwidth=50%,pdfwidth=50%,width=50%]


Nossas descriĂ§Ă”es de cenĂĄrios lĂłgicos da seĂ§ĂŁo anterior usaram a
palavra "`then`" (que no portuguĂȘs significa "`entĂŁo`") para marcar as aĂ§Ă”es que seriam realizadas se uma condiĂ§ĂŁo fosse
verdadeira. Algumas linguagens usam `then` como palavra-chave, mas o Java nĂŁo.
Em vez disso, observe a chave esquerda (`{`) e a chave direita (`}`) que
delimitam a linha executĂĄvel `guardaChuva.pegar();`. Essas chaves desempenham a
mesma funĂ§ĂŁo que a palavra "`then,`", marcando claramente a aĂ§ĂŁo a ser
executada se uma condiĂ§ĂŁo for verdadeira. As chaves sĂŁo inequĂ­vocas porque elas
marcam um inĂ­cio e um fim. Se houver muitas aĂ§Ă”es a serem realizadas, todas elas podem
ser colocadas dentro das chaves, e nĂŁo haverĂĄ dĂșvida sobre quais
aĂ§Ă”es estĂŁo associadas a uma determinada instruĂ§ĂŁo `if`.

Por exemplo, talvez tambĂ©m precisemos fechar a janela e vestir uma capa de chuva
se estiver chovendo. Podemos realizar essas tarefas em Java da seguinte maneira.

[source,java]
----
if (chovendo) {
    guardaChuva.pegar();
    janela.fechar();
    capaDeChuva.vestir();
}
----

Dentro de um par de chaves (`{ }`), chamado de _bloco_ de cĂłdigo,
a execuĂ§ĂŁo prossegue normalmente, linha por linha. Primeiro, a JVM farĂĄ com que o
guarda-chuva seja pegado, depois a janela seja fechada e, finalmente, a
capa de chuva seja vestida.

Se houver apenas uma Ășnica linha de cĂłdigo dentro de um bloco de cĂłdigo, as
chaves podem ser omitidas. Por exemplo, alguns programadores Java experientes
podem ter escrito nosso primeiro exemplo da seguinte forma.


[source,java]
----
if (chovendo)
    guardaChuva.pegar();
----

Para programadores Java iniciantes, no entanto, Ă© uma boa ideia usar chaves
mesmo quando nĂŁo for necessĂĄrio. Sem chaves, o cĂłdigo pode parecer estar fazendo
uma coisa quando, na verdade, estĂĄ fazendo outra.

Como os programadores muitas vezes precisam escolher entre duas alternativas, o Java
fornece uma instruĂ§ĂŁo `else` para especificar o cĂłdigo que deve ser executado quando a
condiĂ§ĂŁo da instruĂ§ĂŁo `if` for falsa.

Seja `cinquentaReais` uma variĂĄvel `boolean` que Ă© `true` se tivermos pelo
menos R$50 e `false` caso contrĂĄrio. Agora, podemos escolher entre duas
opĂ§Ă”es de jantar com base em quanto dinheiro temos.

[source,java]
----
if (cinquentaReais) {
    jantarLagosta.comer();
} else {
    fastFood.comer();
}
----

Este cĂłdigo Java corresponde Ă s instruĂ§Ă”es lĂłgicas que escrevemos anteriormente. Se
tivermos dinheiro suficiente, comeremos um jantar de lagosta; caso contrĂĄrio, comeremos fast
food. 

Assim como em uma instruĂ§ĂŁo `if`, usamos chaves para marcar um bloco de cĂłdigo
tambĂ©m para uma instruĂ§ĂŁo `else`. Como uma Ășnica linha de cĂłdigo serĂĄ
executada em cada caso, as chaves sĂŁo opcionais aqui. PoderĂ­amos ter
escrito o cĂłdigo com a mesma funcionalidade da seguinte forma.

[source,java]
----
if (cinquentaReais)
    jantarLagosta.comer();


else
    fastFood.comer();
----

<<figure-else>> mostra o padrĂŁo de execuĂ§ĂŁo condicional
seguido por todas as instruĂ§Ă”es `if` que possuem uma instruĂ§ĂŁo `else` correspondente.

[[figure-else]]
[.text-center]
.A execuĂ§ĂŁo ocorre dentro da instruĂ§ĂŁo `if` quando sua condiĂ§ĂŁo Ă© `true` e salta para a instruĂ§ĂŁo `else` caso contrĂĄrio.


image::else.svg[scaledwidth=50%,pdfwidth=50%,width=50%]


.Armadilha: IndentaĂ§ĂŁo enganosa
[AVISO]
====

A indentaĂ§ĂŁo Ă© usada para tornar o cĂłdigo mais legĂ­vel, mas o Java ignora
espaĂ§os em branco, o que significa que a indentaĂ§ĂŁo nĂŁo tem efeito sobre a execuĂ§ĂŁo
do cĂłdigo. 

Para demonstrar, vamos supor que nosso cliente imaginĂĄrio saiba
que terĂĄ dor de estĂŽmago depois de comer fast food. Assim, ele tomarĂĄ
um pouco de Pepto-Bismol depois de comer. Se vocĂȘ adicionasse essa aĂ§ĂŁo ao cĂłdigo acima, que
nĂŁo contĂ©m chaves, poderia obter o seguinte.

[source,java]
----
if (cinquentaReais)
    jantarLagosta.comer();
else
    fastFood.comer();
    peptoBismol.pegar();
----

Embora pareĂ§a que tanto `fastFood.comer();` quanto `peptoBismol.pegar();`
estejam dentro do bloco da instruĂ§ĂŁo `else`, apenas `fastFood.comer();` estĂĄ.


A linha `peptoBismol.pegar();` nĂŁo faz parte da estrutura `if`-`else`
de forma alguma e serĂĄ executada independentemente do que acontecer. Portanto, chaves sĂŁo necessĂĄrias, conforme mostrado
abaixo.

[source,java]
----

if (cinquentaReais)
    jantarLagosta.comer();
else {
    fastFood.comer();
    peptoBismol.pegar();
}
----

Esse tipo de confusĂŁo pode ser evitado se sempre forem usadas chaves. Muitos guias de estilo
insistem no uso constante de chaves, portanto, adotaremos esse estilo pelo resto
do livro.

====

==== O tipo `boolean` e suas operaĂ§Ă”es

Lembre-se de que Java usa o tipo `boolean` para valores que sĂł podem ser
`true` ou `false`. Assim como os tipos numĂ©ricos `double` e `int`, o
tipo `boolean` possui operaĂ§Ă”es especĂ­ficas que podem ser usadas para combinĂĄ-los
entre si. Por definiĂ§ĂŁo, essas operaĂ§Ă”es correspondem exatamente Ă s operaĂ§Ă”es lĂłgicas
que descrevemos anteriormente. Aqui estĂĄ uma tabela apresentando os operadores Java
equivalentes Ă s operaĂ§Ă”es lĂłgicas booleanas.

[.center%autowidth%unbreakable%header,cols="^.^,^.^,^.^,<.^",]
|=======================================================================
^.>|Nome
^.>|MatemĂĄtica +
SĂ­mbolo
^.>|Java +
Operador
<.>|DescriĂ§ĂŁo
|AND |â§ |`&&` |Retorna `true` se ambos os valores forem `true`
|OR |âš |`\|\|` |Retorna `true` se qualquer um dos valores for `true`
|XOR |â |`^` |Retorna `true` se os valores forem diferentes
|NOT |ÂŹ |`!` |Retorna o oposto do valor
|=======================================================================

Usando esses operadores, podemos criar valores `boolean` e combinĂĄ-los
entre si.

[source,java]
----
boolean x = true;
boolean y = false;
boolean z = !((x || y) ^ (x && y));
----

Quando este cĂłdigo for executado, o valor de `z` serĂĄ `false`. Embora
seja perfeitamente vĂĄlido realizar operaĂ§Ă”es `boolean` dessa maneira, Ă©
muito mais comum combinĂĄ-las "`na hora`" dentro da condiĂ§ĂŁo
de uma instruĂ§ĂŁo `if`. Lembre-se da instruĂ§ĂŁo da seĂ§ĂŁo anterior:

====
_Se eu estiver entediado, ou se for tarde e eu nĂŁo conseguir dormir,_
=====
_eu vou assistir televisĂŁo._
=====
====

Se considerarmos `cansado`, `tarde` e `podeDormir` como variĂĄveis `boolean` cujos
valores indicam se estamos entediados, se Ă© tarde e se podemos dormir,
respectivamente, podemos codificar essa instruĂ§ĂŁo em Java da seguinte maneira.

[source,java]
----
if (cansado || (tarde && !podeDormir)) {
    televisao.assistir();
}
----

Combinar o operador `||` com outros operadores `||` Ă© tanto
comutativo quanto associativo: a ordem e o agrupamento nĂŁo importam.
Da mesma forma, combinar o operador `&&` com outros operadores `&&` Ă©
tambĂ©m comutativo e associativo. No entanto, quando vocĂȘ comeĂ§a a misturar `||`
com `&&`, Ă© uma boa ideia usar parĂȘnteses para agrupar. Se, no
exemplo acima, `cansado` for `true`, `tarde` for `false` e `podeDormir`
for `true`, entĂŁo a expressĂŁo `cansado || (tarde && !podeDormir)` serĂĄ
`true`. No entanto, com os mesmos valores, a expressĂŁo
`cansado || tarde && !podeDormir` serĂĄ `false`.

Agora que estamos discutindo a ordem, observe que `||`
e `&&` sĂŁo operadores de _curto-circuito_. Curto-circuito significa que, se
o valor da expressĂŁo puder ser determinado sem avaliar o
resto dela, a JVM nĂŁo se darĂĄ ao trabalho de calcular mais nada da
expressĂŁo. Com `||`, essa situaĂ§ĂŁo ocorre porque `true` `OU` qualquer
outra coisa ainda Ă© `true`. Com `&&`, essa situaĂ§ĂŁo ocorre porque `false`
`E` qualquer outra coisa ainda Ă© `false`.

[source,java]
----
if (true || ((tarde && !podeDormir && cansado & temFome) ||
    (querDescobrirOQueAconteceA seguirNoSeuProgramaFavorito ||
    gostaDeTV)))
----

A condiĂ§ĂŁo desta instruĂ§ĂŁo `if` sempre serĂĄ avaliada como `true`, e
seu corpo sempre serĂĄ executado. Como o Java sabe disso, ele nem
se darĂĄ ao trabalho de verificar nenhuma das condiĂ§Ă”es apĂłs o primeiro operador `||`.
Essa avaliaĂ§ĂŁo de curto-circuito Ă© feita em tempo de execuĂ§ĂŁo e funcionarĂĄ se o
valor de uma variĂĄvel no inĂ­cio de uma clĂĄusula OR for `true`. NĂŁo precisa
ser o literal `true`.

[source,java]
----
if (false && ((tarde || !poderdormir || cansado || temFome) &&
    (querDescobrirOQueAconteceA seguirNoSeuProgramaFavorito ||
    gostaDeTV)))
----

A condiĂ§ĂŁo desta instruĂ§ĂŁo `if` sempre serĂĄ avaliada como `false` e
seu trecho nĂŁo serĂĄ executado. Como antes, nada apĂłs o primeiro `&&`
serĂĄ sequer verificado. Se vocĂȘ estiver combinando literais e valores `boolean`
com os operadores `||` e `&&`, nĂŁo faz diferenĂ§a que
ocorra a avaliaĂ§ĂŁo de curto-circuito. No entanto, se uma chamada de mĂ©todo fizer parte das
clĂĄusulas, seu cĂłdigo pode perder efeitos colaterais valiosos. Por exemplo,
suponha que a variĂĄvel `boolean` `trabalhando` seja `false` no exemplo a seguir.

[source,java]
----
if (trabalhando & fazerAlgoImportante())
----

Nesse caso, o mĂ©todo `fazerAlgoImportante()` deve retornar um
valor `boolean` para ser uma instruĂ§ĂŁo vĂĄlida. Ainda assim, se `trabalhando` for `false`,
o mĂ©todo âfazerAlgoImportante()â nem mesmo serĂĄ chamado. Assim que a
JVM perceber que estĂĄ aplicando a operaĂ§ĂŁo `&&` a um valor `false`
(ou um `||` a um `true`), ela desistirĂĄ. Em muitos casos, fazer isso Ă© aceitĂĄvel. Na verdade,
os programadores Ă s vezes exploram esse recurso para permitir que o cĂłdigo em um
mĂ©todo como `fazerAlgoImportante()` seja executado apenas se for seguro fazĂȘ-lo.
Nesse caso, se assumirmos que sempre queremos executar o
mĂ©todo `fazerAlgoImportante()` (porque ele faz algo importante)
sempre que a condiĂ§ĂŁo da instruĂ§ĂŁo `if` for avaliada, precisamos
reestruturar o cĂłdigo. Por exemplo, podemos inverter a ordem dos dois
termos na clĂĄusula `AND` para obter esse efeito. Alternativamente, o Java
fornece versĂ”es sem curto-circuito dos operadores `||` e `&&`,
ou seja, `|` e `&`, caso vocĂȘ precise forĂ§ar a avaliaĂ§ĂŁo completa.

VocĂȘ deve estar se perguntando de onde vem a maioria dos valores `boolean`
. A maioria dos programas de computador nĂŁo faz ao usuĂĄrio uma longa sĂ©rie de perguntas do tipo verdadeiro
ou falso antes de apresentar uma resposta. A maioria dos valores `boolean`
em programas Java Ă© resultado de comparaĂ§Ă”es, frequentemente de tipos de dados numĂ©ricos
.

Pode ser Ăștil comparar dois nĂșmeros para ver se um Ă© maior, menor ou
igual ao outro. Por exemplo, vocĂȘ pode ter uma variĂĄvel `double`
chamada `pressao` que fornece a pressĂŁo da ĂĄgua em um sistema hidrĂĄulico.
Talvez vocĂȘ tambĂ©m tenha uma constante chamada `PRESSAO_CRITICA` que fornece
a pressĂŁo mĂĄxima segura para o seu sistema. VocĂȘ pode comparar esses valores
usando o operador `>`.

[source,java]
----
if (pressao > PRESSAO_CRITICA) {
    desligamentoDeEmergencia();
}
----

Este cĂłdigo permite que vocĂȘ chame o mĂ©todo de emergĂȘncia apropriado quando
`pressao` estiver muito alta. Ă claro que o operador `>` nĂŁo Ă© a Ășnica maneira
de comparar dois valores em Java. Listamos todos os operadores relacionais em
<<strings-primitive-types#strings-primitive-types>>, mas
a tabela abaixo os mostra novamente em um
contexto matemĂĄtico.

[.center%autowidth,cols="<.^,^.^,^.^,<.^",options="header",]
.Operadores relacionais
|=======================================================================
<.>|Nome
^.>|MatemĂĄtica +
SĂ­mbolo
^.>|Java +
Operador
<.>|DescriĂ§ĂŁo
|Igual |= |`==` |`true` se os dois valores forem iguais
|Diferente |â  |`!=` |`true` se os dois valores nĂŁo forem
iguais
|Menor que |< |`<` |`true` se o primeiro valor for estritamente
menor que o segundo
|Menor ou igual a |â€ |`\<=` |`true` se o primeiro
valor for menor ou igual ao segundo
|Maior que |> |`>` |`true` se o primeiro valor for
estritamente maior que o segundo
|Maior ou igual a |â„ |`>=` |`true` se o primeiro
valor for maior ou igual ao segundo
|=======================================================================


Os conceitos e sĂ­mbolos matemĂĄticos para esses operadores devem ser
familiares da matemĂĄtica. Existem algumas diferenĂ§as em relaĂ§ĂŁo Ă s
versĂ”es matemĂĄticas desses conceitos que vale a pena destacar. Primeiro,
apenas sĂ­mbolos fĂĄceis de digitar sĂŁo usados para os operadores Java. Assim, precisamos de dois
caracteres para representar a maioria dos operadores relacionais na linguagem. Esses operadores
podem ser usados para comparar qualquer tipo numĂ©rico com qualquer outro tipo numĂ©rico,
incluindo `char`. No caso de tipos incompatĂ­veis, como um `int` e
um `double`, o tipo de menor precisĂŁo Ă© automaticamente convertido para o tipo de maior
precisĂŁo. Deve-se ter cuidado ao usar o operador `==` com
tipos de ponto flutuante devido a erros de arredondamento. Por exemplo, a
expressĂŁo `1.0/3.0 == 0.3333333333` sempre resulta em `false`.

O operador `==` nĂŁo Ă© o mesmo que o operador `=` dos capĂ­tulos anteriores
. Em Java, o sinal de igual duplo `==` Ă© usado para comparar duas
coisas, enquanto o sinal de igual simples `=` Ă© usado para atribuir uma coisa a
outra.

TambĂ©m pode haver confusĂŁo porque, no mundo da matemĂĄtica, os sĂ­mbolos relacionais
sĂŁo usados para fazer uma afirmaĂ§ĂŁo: _x_ < _y_ Ă© uma
afirmaĂ§ĂŁo ou uma constataĂ§ĂŁo de que o valor contido em _x_
Ă©, de fato, menor do que o valor contido em _y_. No 
mundo Java, a afirmaĂ§ĂŁo `x < y` Ă© um *teste* cuja resposta Ă© `true` se
o valor contido em `x` for menor que o valor contido em `y`
e `false` caso contrĂĄrio. Usar esses operadores significa realizar um teste em
um ponto especĂ­fico do cĂłdigo, fazendo uma pergunta sobre os valores que
certas variĂĄveis ou literais (ou os resultados de chamadas de mĂ©todo) tĂȘm naquele
momento. Em outro sentido, usar essas comparaĂ§Ă”es Ă© uma maneira
de pegar dados numĂ©ricos e convertĂȘ-los na linguagem de valores `boolean`
. Observe que o cĂłdigo a seguir nĂŁo compila em Java.

[source,java]
----
if (4) {
    x = y + z;
}
----

Para ser usado em uma instruĂ§ĂŁo `if`, o valor `4` deve primeiro ser comparado
com algum outro tipo numĂ©rico para produzir um `true` ou `false`. +

.Armadilha: AtribuiĂ§ĂŁo em vez de igualdade
[AVISO]
====

Uma armadilha comum Ă© esquecer um dos sinais de igual
no operador de comparaĂ§ĂŁo.

[source,java]
----
if (x = 4) {
    x = y + z;
}
----

Novamente, este cĂłdigo nĂŁo serĂĄ compilado. Se fosse, a variĂĄvel `x` teria
atribuĂ­do o valor `4`, que por sua vez seria passado para a instruĂ§ĂŁo `if`,
mas uma instruĂ§ĂŁo `if` nĂŁo sabe o que fazer com nada
alĂ©m de um valor `boolean`.

Ă preciso ter extremo cuidado ao
comparar dois valores `boolean`. Por exemplo, podemos ter dois valores `boolean`
"gostaDeCaes1" e "gostaDeCaes2", correspondendo ao fato de duas
pessoas diferentes gostarem ou nĂŁo de cĂŁes. Digamos que o valor de cada um seja `true` se a
pessoa gosta de cĂŁes e `false` caso contrĂĄrio. PoderĂ­amos criar uma instruĂ§ĂŁo `if`
que funcionaria apenas se seus valores fossem iguais.

[source,java]
----
if (gostaDeCaes1 == gostaDeCaes2) {
    fazerColegasDeQuarto();
}
----

Este cĂłdigo chama corretamente o mĂ©todo `fazerColegasDeQuarto()` apenas se as duas
pessoas tiverem a mesma opiniĂŁo sobre cĂŁes. NĂŁo importa se ambas gostam
ou nĂŁo gostam de cĂŁes, mas um colega de quarto que ama cĂŁes e outro que odeia cĂŁes levarĂĄ a problemas. 
No entanto, um pequeno erro no cĂłdigo poderia resultar no seguinte.

[source,java]
----
if (gostaDeCaes1 = gostaDeCaes2) {
    fazerColegasDeQuarto();
}
----

Nesse caso, `gostaDeCaes1` seria atribuĂ­do ao valor de `gostaDeCaes2`.
EntĂŁo, esse valor seria passado para a instruĂ§ĂŁo `if`. Aqui, o mĂ©todo `fazerColegasDeQuarto()` serĂĄ chamado apenas se `gostaDeCaes2`
for `true`, o que significa que a segunda pessoa gosta de cĂŁes. Assim, as duas pessoas se tornarĂŁo colegas de quarto se
a segunda pessoa gosta de cĂŁes, e os sentimentos da primeira pessoa nĂŁo serĂŁo
considerados. Ao contrĂĄrio do exemplo `x = 4`, este cĂłdigo serĂĄ compilado sem nenhum aviso.

====

Os prĂłximos exemplos ilustram o uso da instruĂ§ĂŁo `if`. Eles
tambĂ©m utilizam alguns mĂ©todos da classe `Math`.


[[leapYearExample]]
.Ano bissexto
====

No calendĂĄrio gregoriano padrĂŁo, os anos bissextos ocorrem aproximadamente uma vez a cada
quatro anos. Durante os anos bissextos, o mĂȘs de fevereiro tem 29 dias em vez
de 28. Esse dia extra compensa o fato de que a Terra leva um pouco mais de 365,24
dias para orbitar o Sol. Infelizmente, a Ăłrbita da
Terra ao redor do Sol nĂŁo coincide de forma exata com a
rotaĂ§ĂŁo da Terra, criando exceĂ§Ă”es Ă  regra de a cada
quatro anos.

Na verdade, a definiĂ§ĂŁo oficial de um ano bissexto Ă© um ano que Ă©
divisĂ­vel por 4, exceto aqueles anos que sĂŁo divisĂ­veis
por 100, com a exceĂ§ĂŁo dos anos que sĂŁo
divisĂ­veis por 400. Por exemplo, 1988 foi um ano bissexto porque era
divisĂ­vel por 4. O ano de 1900 nĂŁo foi um ano bissexto porque era
divisĂ­vel por 100, mas nĂŁo por 400, e o ano de 2000 foi um ano bissexto
porque era divisĂ­vel por 400.

Lembre-se de que o operador mod (`%`) nos permite encontrar o resto
apĂłs a divisĂŁo inteira. Assim, se `n % 100` for zero, `n` nĂŁo tem
resto apĂłs ser dividido por `100` e deve ser divisĂ­vel por
100.

.Solicita ao usuĂĄrio um ano e, em seguida, determina se Ă© ou nĂŁo um ano bissexto.
[source, java]
[[LeapYearProgram]]
----
include::{programsdir}/LeapYear.java[]
----

Assim como em todos os programas desta seĂ§ĂŁo, comeĂ§amos importando
`java.util.*`, necessĂĄrio para a classe `Scanner` de entrada. O
programa solicita ao usuĂĄrio que digite um ano e o lĂȘ. Se o ano for
divisĂ­vel por 400, o programa exibe que Ă© um ano bissexto.
Caso contrĂĄrio, se o ano for divisĂ­vel por 100, o programa exibe
que nĂŁo Ă© um ano bissexto. Caso contrĂĄrio, se o ano for divisĂ­vel
por 4, o programa exibe que Ă© um ano bissexto. Por fim, se todas as
outras condiĂ§Ă”es falharem, o programa exibe que o ano nĂŁo Ă© um
ano bissexto.

====

.FĂłrmula quadrĂĄtica
====

A fĂłrmula quadrĂĄtica Ă© uma ferramenta Ăștil da matemĂĄtica. Usando essa
fĂłrmula, vocĂȘ pode resolver equaĂ§Ă”es da forma _ax_^2^ + _bx_
+ _c_ = 0. VocĂȘ deve se lembrar da formulaĂ§ĂŁo da fĂłrmula quadrĂĄtica apresentada abaixo.

//[stem]
//++++
//\frac{-b \pm \sqrt{b^2 - 4ac}}{2a}
//++++

[.text-center]
image::quadratic.svg[scaledwidth=20%,pdfwidth=20%,width=20%]

A parte _b_^2^ - 4__ac__ da fĂłrmula Ă© chamada de
_discriminante_. Se o discriminante for positivo, haverĂĄ duas
respostas reais para a equaĂ§ĂŁo. Se o discriminante for negativo, haverĂĄ
duas respostas complexas para a equaĂ§ĂŁo. Finalmente, se o discriminante for
zero, haverĂĄ uma Ășnica resposta real para o problema. Se vocĂȘ quiser
escrever um programa para resolver equaĂ§Ă”es quadrĂĄticas, ele deve levar
essas trĂȘs possibilidades em consideraĂ§ĂŁo.

.Resolve uma equaĂ§ĂŁo quadrĂĄtica.
[source, java]
[[QuadraticProgram]]
----
include::{programsdir}/Quadratic.java[]
----
<.> Este programa solicita ao usuĂĄrio e lĂȘ os valores de `a`,
`b` e `c`.
<.> Em seguida, ele calcula o discriminante. 
<.> No primeiro caso, verificamos se o discriminante Ă© zero e imprimimos a Ășnica resposta.
<.> Em seguida, se o discriminante for negativo, calculamos as partes real e complexa separadamente e exibimos as
duas respostas.
<.> Finalmente, se o discriminante for positivo, encontramos as duas respostas reais
e as exibimos.

A condiĂ§ĂŁo `discriminante == 0.0` Ă© perigosa, pois estamos usando
valores `double`. Devido a erros de arredondamento, o discriminante pode nĂŁo
ser exatamente zero, mesmo que devesse ser, matematicamente. Um cĂłdigo de nĂ­vel industrial
provavelmente verificaria se o valor absoluto do
discriminante Ă© menor que um nĂșmero muito pequeno (como 0.00000001).
Valores tĂŁo pequenos seriam entĂŁo tratados como se fossem zero.

====

.20 Perguntas
====

No tradicional jogo das 20 Perguntas, uma pessoa escolhe mentalmente
algo, e os outros participantes devem adivinhar o que Ă©
fazendo perguntas cuja resposta seja "`sim`" ou "`nĂŁo`". Em uma
versĂŁo popular, a pessoa que escolhe o objeto comeĂ§a declarando
se Ă© animal, vegetal ou mineral.

Usando princĂ­pios de contagem da matemĂĄtica, 20 perguntas de sim ou nĂŁo tornam
possĂ­vel diferenciar 2^20 = 1.048.576 itens. Se vocĂȘ tambĂ©m souber 
se a coisa Ă© animal, vegetal ou
mineral, deve ser possĂ­vel adivinhar mais de 3 milhĂ”es de itens! Neste ponto
de nosso desenvolvimento como programadores Java, ainda nĂŁo estamos
prontos para lidar com uma gama tĂŁo grande de possibilidades. Para manter o
tamanho do cĂłdigo razoĂĄvel, vamos restringir o campo a 10 itens diferentes
: um lagarto, uma ĂĄguia, um golfinho, um ser humano, um pouco de chumbo, um diamante, um
tomate, um pĂȘssego, uma ĂĄrvore de bordo e uma batata.

[[figure-flowchart]]
.Ărvore de decisĂŁo para distinguir 10 itens.
image::flowchart.svg[scaledwidth=100%,pdfwidth=100%,width=100%]


Usando esses itens, podemos construir uma ĂĄrvore de decisĂ”es,
comeĂ§ando com a decisĂŁo entre animal, vegetal e mineral. Se
a coisa for um animal, poderĂ­amos entĂŁo perguntar se Ă© um mamĂ­fero. Se *for* um
mamĂ­fero, poderĂ­amos perguntar se vive em terra, decidindo entre humano e
golfinho. Se *nĂŁo* for um mamĂ­fero, poderĂ­amos perguntar se voa, decidindo
entre uma ĂĄguia e um lagarto. Podemos construir perguntas semelhantes para
as coisas nas categorias vegetal e mineral, correspondendo a
<<figure-flowchart>>.

.Navega pelas escolhas possĂ­veis na ĂĄrvore de decisĂŁo.
[source, java]
[[TwentyQuestionsProgram]]
----
include::{programsdir}/TwentyQuestions.java[]
----

O cĂłdigo neste exemplo Ă© simples, embora mesmo 10 itens
resultem em muitos blocos `if` e `else`. AlĂ©m das instruĂ§Ă”es `if`-`else`,
apenas entradas e saĂ­das simples sĂŁo necessĂĄrias para que o programa
funcione. Para uma comparaĂ§ĂŁo `String` adequada, Ă© necessĂĄrio usar o
mĂ©todo `equals()` para testar se dois valores `String` sĂŁo iguais.

Observe que adicionamos comentĂĄrios especificando o que presumimos ser o caso
para cada bloco `else`. Se fĂŽssemos mais cuidadosos, deverĂ­amos testar
os casos `"y"` e `"n"` e, entĂŁo, exibir uma mensagem de erro quando o usuĂĄrio
inserisse algo inesperado, como `"x"`, `â149â` ou mesmo `"no"`.

VocĂȘ pode estar curioso para saber como criar um jogo de 20 Perguntas de verdade que possa
aprender com o tempo. Para isso, sĂŁo necessĂĄrias muitas outras ferramentas de programaĂ§ĂŁo:
repetiĂ§ĂŁo, estruturas de dados (para que vocĂȘ possa organizar as perguntas),
e entrada e saĂ­da de arquivos (para que vocĂȘ possa armazenar novas informaĂ§Ă”es
permanentemente). Esses conceitos sĂŁo abordados em capĂ­tulos posteriores.

====


==== InstruĂ§Ă”es `switch`

_Esta seĂ§ĂŁo descreve a instruĂ§ĂŁo `switch` tal como foi definida nas versĂ”es anteriores ao Java 12 e 14. <<_expressĂ”es_switch>> descreve as melhorias que permitem que o `switch` seja usado em qualquer lugar onde uma expressĂŁo seja utilizada._

A instruĂ§ĂŁo `if` Ă© o carro-chefe da execuĂ§ĂŁo condicional em Java. Com
o devido cuidado, vocĂȘ pode criar cĂłdigo capaz de tomar qualquer sequĂȘncia fixa de
decisĂ”es com complexidade arbitrĂĄria. Mesmo assim, a instruĂ§ĂŁo `if` pode ser
um pouco desajeitada, pois permite apenas escolher entre duas
alternativas. Afinal, uma condiĂ§ĂŁo sĂł pode ser `true` ou `false`.
Certamente, as decisĂ”es podem ser aninhadas, permitindo mais de duas
possibilidades, mas longas listas de possibilidades podem ser pesadas e difĂ­ceis de ler.

Por exemplo, imagine que queremos criar um programa que determine
o presente apropriado para um aniversĂĄrio de casamento. Abaixo estĂĄ uma tabela de
categorias tradicionais de presentes com base no ano de aniversĂĄrio.

[.center%autowidth%unbreakable,cols="^.^,<.^,^,^.^,<.^",]
|=================================
|Ano |Presente | |Ano |Presente

|1 |Papel | |13 |Renda
|2 |AlgodĂŁo | |14 |Marfim
|3 |Couro | |15 |Cristal
|4 |Fruta | |20 |Porcelana
|5 |Madeira | |25 |Prata
|6 |Doces / Ferro | |30 |PĂ©rola
|7 |LĂŁ / Cobre | |35 |Coral
|8 |Bronze / CerĂąmica | |40 |Rubi
|9 |CerĂąmica / Salgueiro | |45 |Safira
|10 |Estanho / AlumĂ­nio | |50 |Ouro
|11 |AĂ§o | |55 |Esmeralda
|12 |Seda / Linho | |60 |Diamante
|=================================

Seja `ano` uma variĂĄvel do tipo `int` contendo o ano em questĂŁo.
Uma estrutura de instruĂ§Ă”es `if`-`else` que pode determinar o presente apropriado
com base no ano estĂĄ abaixo.

[source,java]
----
String gift;
if (ano == 1) {
    presente = "Papel";
} else if (ano == 2) {
    presente = "AlgodĂŁo";
} else if (ano == 3) {
    presente = "Couro";
} else if (ano == 4) {
    presente = âFrutaâ;
} else if (ano == 5) {
    presente = "Madeira";
} else if (ano == 6) {
    presente = "Doces / Ferro";
} else if (ano == 7) {
    presente = "LĂŁ / Cobre";
} else if (ano == 8) {
    presente = "Bronze / CerĂąmica";
} else if (ano == 9) {
    presente = "CerĂąmica / Salgueiro";
} else if (ano == 10) {
    presente = "Estanho / AlumĂ­nio";
} else if (ano == 11) {
    presente = âAĂ§oâ;
} else if (ano == 12) {
    presente = "Seda / Linho";
} else if (ano == 13) {
    presente = "Renda";
} else if (ano == 14) {
    presente = "Marfim";
} else if (ano == 15) {
    presente = "Cristal";
} else if (ano == 20) {
    presente = âPorcelanaâ;
} else if (ano == 25) {
    presente = "Prata";
} else if (ano == 30) {
    presente = "PĂ©rola";
} else if (ano == 35) {
    presente = "Coral";
} else if (ano == 40) {
    presente = âRubiâ;
} else if (ano == 45) {
    presente = "Safira";
} else if (ano == 50) {
    presente = "Ouro";
} else if (ano == 55) {
    presente = "Esmeralda";
} else if (ano == 60) {
    presente = âDiamanteâ;
} else {
    presente = "Sem presente tradicional";
}
----

Este cĂłdigo armazena o valor correto em `presente`. Observe que estamos usando a
caracterĂ­stica das instruĂ§Ă”es `if` que trata uma instruĂ§ĂŁo `if` inteira como uma Ășnica
instruĂ§ĂŁo. Se usĂĄssemos chaves para agrupar as coisas como elas realmente sĂŁo, com o
conteĂșdo de cada `else` indentado com cada `if` aninhado dentro, o cĂłdigo
se tornaria ilegĂ­vel e excessivamente grande.

[source,java]
----
String presente;
if (ano == 1) {
    presente = "Papel";
} else {
    if (ano == 2) {
        presente = âAlgodĂŁoâ;
    } else {
        if (ano == 3) {
            presente = "Couro";
        
} else {
            if (ano == 4) {
                present= "Fruit";
            }
            .
            .
            .
----

Parece que existe algum tipo de construĂ§ĂŁo `else if` em Java, mas
nĂŁo existe. Ainda assim, o uso cuidadoso das regras para chaves nos permite
escrever cĂłdigo que expressa bem uma sequĂȘncia de alternativas.

Outra maneira de expressar uma longa sequĂȘncia de alternativas Ă© usando uma
instruĂ§ĂŁo `switch`. Uma instruĂ§ĂŁo `switch` recebe um Ășnico valor do tipo inteiro
(`int`, `long`, `short`, `byte`, `char`) ou uma `String` e salta
para um caso correspondente Ă  entrada. Podemos reescrever o exemplo do presente de aniversĂĄrio
usando uma instruĂ§ĂŁo `switch` da seguinte maneira.

[source#gift-switch-statement,java]
----
String presente;
switch (ano) {
    case 1: presente = "Papel"; break;
    case 2: presente = "AlgodĂŁo"; break;
    case 3: presente = "Couro"; break;
    case 4: presente = âFrutaâ; break;
    case 5: presente = "Madeira"; break;
    case 6: presente = "Doces / Ferro"; break;
    case 7: presente= "LĂŁ / Cobre"; break;
    case 8: presente= "Bronze / CerĂąmica"; break;
    case 9: presente= "CerĂąmica / Salgueiro"; break;
    case 10: presente= "Estanho / AlumĂ­nio"; break;
    caso 11: presente = "AĂ§o"; break;
    caso 12: presente = "Seda / Linho"; break;
    caso 13: presente = "Renda"; break;
    caso 14: presente = âMarfimâ; break;
    caso 15: presente = "Cristal"; break;
    caso 20: presente = "Porcelana"; break;
    caso 25: presente = "Prata"; break;
    caso 30: presente = "PĂ©rola"; break;
    caso 35: presente = "Coral"; break;
    caso 40: presente = âRubiâ; break;
    caso 45: presente = "Safira"; break;
    case 50: presente = "Ouro"; break;
    case 55: presente = "Esmeralda"; break;
    case 60: presente = âDiamanteâ; break;
    default: presente = "Sem presente tradicional"; break;
}
----

Assim como uma instruĂ§ĂŁo `if`, uma instruĂ§ĂŁo `switch` sempre possui parĂȘnteses
que envolvem algum argumento. Ao contrĂĄrio de um `if`, o argumento de um `switch` bĂĄsico deve
ser algum tipo de dado que possa ser expresso como um inteiro ou uma `String`,
nĂŁo um `boolean`. (Na prĂłxima seĂ§ĂŁo, veremos que, em versĂ”es mais recentes do Java, o argumento do `switch` pode ser mais complexo.) Para cada um dos valores possĂ­veis que vocĂȘ deseja que o `switch`
trate, vocĂȘ escreve uma instruĂ§ĂŁo `case`. Uma instruĂ§ĂŁo `case` consiste em
a palavra-chave `case` seguida por um valor constante, seja um literal ou uma
constante nomeada, e depois dois pontos. Quando executada, a JVM salta para o
rĂłtulo `case` correspondente e comeĂ§a a executar o cĂłdigo ali. Se nĂŁo houver
rĂłtulo `case` correspondente, a JVM vai para o rĂłtulo `default`. Se nĂŁo houver
rĂłtulo `default`, toda a instruĂ§ĂŁo `switch` Ă© ignorada.

Uma caracterĂ­stica incomum das instruĂ§Ă”es `switch` Ă© que a execuĂ§ĂŁo _passa
pelas_ instruĂ§Ă”es `case`. Isso significa que vocĂȘ pode usar muitas instruĂ§Ă”es
`case` diferentes para um Ășnico segmento de cĂłdigo executĂĄvel. A execuĂ§ĂŁo
do cĂłdigo em uma instruĂ§ĂŁo `switch` salta para fora quando encontra uma instruĂ§ĂŁo `break`
. No entanto, uma instruĂ§ĂŁo `break` nĂŁo Ă© necessĂĄria em todos os `case`, como mostrado nesta instruĂ§ĂŁo `switch` que fornece informaĂ§Ă”es de localizaĂ§ĂŁo para todos os
cĂłdigos de ĂĄrea telefĂŽnica no estado de Nova York. Se um `case` nĂŁo tiver uma instruĂ§ĂŁo `break`, o controle passa para o prĂłximo `case` (ou `default`).

[source,java]
----
String localidade = "";
switch (codigo) {
    
case 917: localidade = "Celular: ";
    case 212:
    case 347:
    case 646:
    case 718: localidade += "Cidade de Nova York"; break;

    case 315: localidade = âSyracuseâ; break;

    case 516: localidade = "Condado de Nassau"; break;
    
case 518: localidade = "Albany"; break;

    case 585: localidade = âRochesterâ; break;

    case 607: localidade = "Centro-Sul de Nova York"; break;

    case 631: localidade = "Condado de Suffolk"; break;
    
case 716: localidade = "Buffalo"; break;

    case 845: localidade = "Vale do Baixo Hudson"; break;

    case 914: localidade = "Condado de Westchester"; break;

    default: localidade = "CĂłdigo de ĂĄrea desconhecido"; break;
}
----

Como vocĂȘ pode ver, cinco cĂłdigos de ĂĄrea diferentes sĂŁo usados pela cidade de Nova York. Ao
omitir as instruĂ§Ă”es `break`, os valores de `212`, `347`, `646` e
`718` tĂȘm `"Cidade de Nova York"` armazenado em `localidade`. O cĂłdigo de ĂĄrea 917
foi originalmente designado para telefones celulares e pagers, embora agora
inclua alguns telefones fixos. Ao colocar habilmente a instruĂ§ĂŁo para `917` Ă  frente das outras entradas da cidade de Nova York, um valor de `917` primeiro armazena
`"Celular: "` em `localidade` e, em seguida, passa adiante e acrescenta
`"Cidade de Nova York"`. Para cada um desses cinco cĂłdigos de ĂĄrea, a execuĂ§ĂŁo na
instruĂ§ĂŁo `switch` termina somente quando a instruĂ§ĂŁo `break` Ă© alcanĂ§ada.

Os nove cĂłdigos de ĂĄrea restantes sĂŁo separados. Cada um deles faz uma
Ășnica atribuiĂ§ĂŁo e, em seguida, sai do bloco `switch`. Por fim,
o rĂłtulo `default` Ă© usado se o cĂłdigo de ĂĄrea nĂŁo corresponder a um dos
cĂłdigos fornecidos. Observe que ordenamos os cĂłdigos de ĂĄrea (que nĂŁo sĂŁo de Nova York) em
ordem crescente para facilitar a leitura. Conforme mostrado no
exemplo `917`, nĂŁo hĂĄ regra sobre a ordem dos rĂłtulos. AtĂ© mesmo
o rĂłtulo `default` pode ocorrer em qualquer lugar do bloco `switch` que vocĂȘ desejar,
embora seja comum colocĂĄ-lo no final. AlĂ©m disso, o `break` apĂłs o 
rĂłtulo `default` Ă© desnecessĂĄrio, pois a execuĂ§ĂŁo sai do bloco `switch`
de qualquer maneira. No entanto, Ă© sempre aconselhĂĄvel terminar com um `break`, caso
vocĂȘ adicione mais casos posteriormente.

O descuido Ă© sempre algo a se ter cuidado nas instruĂ§Ă”es `switch`
. Deixar de fora uma instruĂ§ĂŁo `break` pode causar bugs desastrosos e
difĂ­ceis de detectar. O compilador tambĂ©m nĂŁo avisa sobre a falta de
instruĂ§Ă”es `break`. Ă inteiramente sua responsabilidade usĂĄ-las
adequadamente. Devido aos riscos envolvidos, muitas vezes Ă© mais seguro
usar instruĂ§Ă”es `if`-`else`. Qualquer instruĂ§ĂŁo `switch` pode ser reescrita como
alguma combinaĂ§ĂŁo de instruĂ§Ă”es `if`-`else`, mas o inverso nĂŁo Ă© verdadeiro.
A vantagem das instruĂ§Ă”es `switch` Ă© sua capacidade de listar muitas
alternativas de forma clara. Suas desvantagens incluem a facilidade de cometer um
erro, a incapacidade de expressar intervalos de dados ou a maioria dos tipos (`double`,
`float` ou qualquer tipo de referĂȘncia que nĂŁo seja `String`) e o
poder de expressĂŁo limitado. Elas devem ser usadas apenas quando a vantagem de exibir claramente
uma lista de dados superar as desvantagens.

A seguir, apresentamos vĂĄrios exemplos para ajudĂĄ-lo a se familiarizar mais com
as instruĂ§Ă”es `switch`.

.Dias do mĂȘs
====

HĂĄ menos usos para as instruĂ§Ă”es `switch` do que para as instruĂ§Ă”es `if`.
No entanto, hĂĄ problemas em que seu
comportamento de falha pode ser Ăștil. Imagine que vocĂȘ precise escrever um
programa que forneĂ§a a duraĂ§ĂŁo de cada mĂȘs (partindo do pressuposto de que fevereiro sempre
tem 28 dias). Dado o mĂȘs como um nĂșmero, podemos usar instruĂ§Ă”es `switch` para escrever um programa
que mapeie o nĂșmero do mĂȘs para o nĂșmero de dias que ele contĂ©m.

.Calcula o nĂșmero de dias em um determinado mĂȘs.
[source, java]
[[DaysInMonthProgram]]
----
include::{programsdir}/DaysInMonth.java[]
----

<.> Este programa tem um Ășnico rĂłtulo para fevereiro, definindo `days` como 28.
<.> Em seguida,
hĂĄ rĂłtulos para abril, junho, setembro e novembro, meses que
tĂȘm, cada um, 30 dias.
<.> Por fim, o grande bloco de janeiro, marĂ§o, maio,
julho, agosto, outubro e dezembro define `days` como 31.

Seria
fĂĄcil estender este cĂłdigo para solicitar ao usuĂĄrio um ano, de modo que vocĂȘ pudesse
integrar o cĂłdigo de ano bissexto de cima para o caso de fevereiro. Observe tambĂ©m
que nĂŁo usamos um rĂłtulo `default`. VocĂȘ pode querer definir `days` como
algum valor especial (como `-1`) para meses invĂĄlidos.

Neste programa, Ă© necessĂĄrio inicializar `days` com algum valor, neste caso `0`.
Caso contrĂĄrio, o programa nĂŁo serĂĄ compilado, pois tentarĂĄ imprimir o
valor dentro de `days`, um valor que nĂŁo existirĂĄ se `month` nĂŁo estiver no intervalo de 1 a 12.

====


[[ordinalNumbersExample]]
.NĂșmeros ordinais
====

O termo _nĂșmeros ordinais_ refere-se a nĂșmeros usados para ordenar
dentro de um conjunto de itens: primeiro, segundo, terceiro e assim por diante. Ao escrever
esses nĂșmeros com algarismos em inglĂȘs, Ă© comum acrescentar duas
letras ao final do algarismo para dar ao leitor uma pista de que esses
algarismos devem ser lidos com seus nomes ordinais: 1Âș, 2Âș, 3Âș e assim
por diante.

Ao contrĂĄrio da maioria das coisas em inglĂȘs, as regras para decidir quais duas letras
sĂŁo relativamente simples. Se o nĂșmero terminar em 1, as letras "`st`"
devem ser usadas geralmente. Se o nĂșmero terminar em 2, as letras "`nd`"
devem ser usadas geralmente. Se o nĂșmero terminar em 3, as letras "`rd`"
devem ser usadas geralmente. Para a maioria dos outros nĂșmeros, as letras "`th`"
devem ser usadas. Podemos usar uma instruĂ§ĂŁo `switch` para escrever um programa que
forneĂ§a as terminaĂ§Ă”es ordinais corretas para a maioria dos nĂșmeros, como segue.

.Anexa o sufixo apropriado a um numeral para tornĂĄ-lo um ordinal.
[source, java]
[[OrdinalsProgram]]
----
include::{programsdir}/Ordinals.java[]
----

Este programa solicita e, em seguida, lĂȘ um `int` do usuĂĄrio. Em seguida,
encontramos o resto da divisĂŁo de `number` por 10, obtendo seu
Ășltimo dĂ­gito. Com base nesse dĂ­gito, podemos escolher entre as quatro possibilidades
e gerar o nĂșmero ordinal correto na maioria dos casos. Infelizmente, os
nomes dos nĂșmeros em inglĂȘs tĂȘm uma convenĂ§ĂŁo de nomenclatura inconsistente entre 11 e 19, inclusive,
e os ordinais para qualquer nĂșmero que termine em 11, 12 ou 13 receberĂŁo o sufixo errado
pelo nosso cĂłdigo. Deixamos uma soluĂ§ĂŁo mais completa como exercĂ­cio.
====

****
<<ordinalNumbersExercise>>
****

.Astrologia
====

Muitas culturas praticam a astrologia, uma tradiĂ§ĂŁo segundo a qual o momento do
nascimento de uma pessoa influencia sua personalidade ou futuro. Um elemento importante
da astrologia chinesa Ă© o zodĂ­aco, composto por 12 animais.
Cada ano consecutivo em um ciclo de 12 anos corresponde a um animal.
Como esse sistema se repete, o ano em que se nasce, mĂłdulo 12,
identifica o animal. Abaixo estĂĄ uma tabela com esses valores. Por
exemplo, se vocĂȘ nasceu em 1979, 1979 mod 12 âĄ 11; portanto, vocĂȘ seria um Carneiro.
Observe que essa disposiĂ§ĂŁo se baseia nos anos do calendĂĄrio gregoriano.
Os astrĂłlogos chineses nĂŁo listam o Macaco como o primeiro animal do ciclo.
Observe que os nomes desses animais tambĂ©m sĂŁo, Ă s vezes, traduzidos de maneiras ligeiramente
diferentes.


[.center%autowidth%unbreakable%header,cols="<.>,^.>,^,<.>,^.>"]
|=====================
|Animal | Ano +
mĂłdulo 12| 
|Animal | Ano +
mĂłdulo 12
|Macaco |0 | |Tigre |6
|Galo |1 | |Coelho |7
|CĂŁo |2 | |DragĂŁo |8
|Javali |3 | |Cobra |9
|Rato |4 | |Cavalo |10
|Boi |5 | |Carneiro |11
|=====================

Infelizmente, esta tabela nĂŁo Ă© muito precisa porque se baseia na
numeraĂ§ĂŁo do calendĂĄrio gregoriano. Os anos em questĂŁo, na verdade,
comeĂ§am e terminam com base no Ano Novo ChinĂȘs, que ocorre entre 21 de janeiro
e 20 de fevereiro. Como consequĂȘncia, vocĂȘ pode calcular incorretamente seu animal se
seu aniversĂĄrio for no inĂ­cio do ano. Como calcular a data do
Ano Novo ChinĂȘs Ă© complicado, vamos ignorar esse problema por enquanto
e escrever um programa usando uma instruĂ§ĂŁo `switch` projetada para
exibir corretamente o animal correspondente a um ano de nascimento inserido.

.Determina um animal do zodĂ­aco chinĂȘs com base no ano de nascimento.
[source, java]
[[ChineseZodiacProgram]]
----
include::{programsdir}/ChineseZodiac.java[]
----

[.center%autowidth%unbreakable,cols="<,<,<",]
|=====================================================
|Signo |SĂ­mbolo |Intervalo de datas

|Ăries |O Carneiro |21 de marĂ§o a 19 de abril
|Touro |O Touro |20 de abril a 20 de maio
|GĂȘmeos |Os GĂȘmeos |21 de maio a 20 de junho
|CĂąncer |O Caranguejo |21 de junho a 22 de julho
|LeĂŁo |O LeĂŁo |23 de julho a 22 de agosto
|Virgem |A Virgem |23 de agosto a 22 de setembro
|Libra |A BalanĂ§a |23 de setembro a 22 de outubro
|EscorpiĂŁo |O EscorpiĂŁo |23 de outubro a 21 de novembro
|SagitĂĄrio |O Arqueiro |22 de novembro a 21 de dezembro
|CapricĂłrnio |A Cabra-marinha |22 de dezembro a 19 de janeiro
|AquĂĄrio |O Portador da Ăgua |20 de janeiro a 19 de fevereiro
|Peixes |Os Peixes |20 de fevereiro a 20 de marĂ§o
|=====================================================

Na astrologia ocidental, um elemento importante associado ao
nascimento de uma pessoa tambĂ©m Ă© chamado de signo do zodĂ­aco. As datas para determinar esse tipo
de signo do zodĂ­aco sĂŁo fornecidas pela tabela anterior.

Se vocĂȘ quiser implementar as regras desse zodĂ­aco em cĂłdigo, uma instruĂ§ĂŁo `switch`
Ă© um bom ponto de partida, mas vocĂȘ tambĂ©m precisa colocar instruĂ§Ă”es `if`
para cada mĂȘs para testar o intervalo exato de datas.

.Determina os signos do zodĂ­aco ocidental com base no mĂȘs e dia de nascimento.
[source,java]
[[WesternZodiacProgram]]
----
include::{programsdir}/WesternZodiac.java[]
----

Este programa Ă© apenas um pouco mais complexo do que o programa para o
zodĂ­aco chinĂȘs. VocĂȘ ainda precisa saltar para 12 casos diferentes (numerados
de 1 a 12 em vez de 0 a 11), mas sĂŁo necessĂĄrias informaĂ§Ă”es adicionais sobre o dia para identificar
o signo.


====

==== ExpressĂ”es `switch`

A expressĂŁo `switch`, introduzida no Java 12 e 14, calcula um Ășnico valor e pode ser usada em qualquer lugar onde se espere uma expressĂŁo. Cada `case` deve calcular um Ășnico valor. Existem duas maneiras de indicar o valor que estĂĄ sendo calculado:

. Use a nova instruĂ§ĂŁo `yield E`. A instruĂ§ĂŁo `yield` pode ser considerada como uma instruĂ§ĂŁo `break` â ela interrompe o fluxo da instruĂ§ĂŁo `switch` â, mas tambĂ©m indica o valor a ser usado como resultado.

. Use a nova sintaxe `+case L -> E+`. Essa sintaxe indica que o valor resultante para `case L` Ă© o valor da expressĂŁo `E`. O rĂłtulo `L` pode ser uma lista de rĂłtulos separados por vĂ­rgulas (veja o exemplo abaixo).

Observe que essas duas abordagens nĂŁo podem ser misturadas: uma Ășnica expressĂŁo `switch` usa ou todos os casos da forma `case L:` ou todos os casos da forma `+case L -> E+`.

A expressĂŁo `switch` pode resultar em um cĂłdigo mais simples do que a instruĂ§ĂŁo `switch` tradicional, tornando-a mais fĂĄcil de escrever e manter. O cĂłdigo abaixo calcula o nĂșmero de dias em um determinado mĂȘs, com o mĂȘs indicado por uma abreviaĂ§ĂŁo de trĂȘs letras:

[source,java]
----
int dias =
    switch (mes) {
        case "Jan", "Mar", "Mai", "Jul", "Ago", "Out", "Dez" -> 31;
        case "Abr", "Jun", âSetâ, "Nov" -> 30;
        
case "Fev" -> 28;
        default -> 0;
    };
----

Como outro exemplo, veja abaixo uma expressĂŁo `switch` para calcular o presente de aniversĂĄrio com base no ano (compare com a versĂŁo anterior <<gift-switch-statement,statement version>>).

[source,java]
----
    
String presente =
        switch (ano) {
          case 1 -> "Papel";
          case 2 -> "AlgodĂŁo";
          case 3 -> "Couro";
          case 4 -> "Fruta";
          case 5 -> âMadeiraâ;
          case 6 -> "Doces / Ferro";
          case 7 -> "LĂŁ / Cobre";
          case 8 -> "Bronze / CerĂąmica";
          case 9 -> "CerĂąmica / Salgueiro";
          case 10 -> "Estanho / AlumĂ­nio";
          case 11 -> âAĂ§oâ;
          case 12 -> "Seda / Linho";
          caso 13 -> "Renda";
          caso 14 -> "Marfim";
          caso 15 -> "Cristal";
          caso 20 -> "Porcelana";
          caso 25 -> "Prata";
          caso 30 -> âPĂ©rolaâ;
          caso 35 -> "Coral";
          case 40 -> "Rubi";
          case 45 -> "Safira";
          case 50 -> "Ouro";
          case 55 -> "Esmeralda";
          case 60 -> âDiamanteâ;
          default -> "Sem presente tradicional";
        };
----

==== InstruĂ§Ă”es `switch` sem instruĂ§Ă”es `break`

Como mencionado anteriormente, o uso de instruĂ§Ă”es `break` pode resultar em erros por descuido: ao omitir acidentalmente um `break` ou adicionar um onde nĂŁo Ă© necessĂĄrio. Com a introduĂ§ĂŁo da sintaxe `+case L -> E+`, Ă© possĂ­vel usar uma instruĂ§ĂŁo `switch` sem nenhuma instruĂ§ĂŁo `break`. Cada `case` torna-se um bloco completo, e nĂŁo hĂĄ continuidade para o prĂłximo caso. Se mais de uma instruĂ§ĂŁo for incluĂ­da em um bloco, as instruĂ§Ă”es devem ser delimitadas por chaves (`+{ }+`).

Aqui estĂĄ um exemplo que imprime o nĂșmero de dias no mĂȘs fornecido e usa um sinalizador para indicar se o mĂȘs Ă© vĂĄlido:

[source,java]
----
boolean mesValido = true;
switch (mes) {
    case "Jan", "Mar", "Mai", "Jul", "Ago", "Out", âDezâ ->
        System.out.println("HĂĄ 31 dias em " + mes);
    
case "Abr", "Jun", "Set", "Nov" ->
        System.out.println("HĂĄ 30 dias em " + mes);
    case âFevâ ->
        System.out.println("HĂĄ 28 dias em " + mes);
    
default -> {
        System.out.println("MĂȘs nĂŁo reconhecido: " + mes);
        mesValido = false;
    }
};

if (mesValido) {
    // Continuar o processamento...
}
----

=== SoluĂ§ĂŁo: Monty Hall

Voltamos agora Ă  simulaĂ§ĂŁo de Monty Hall descrita no inĂ­cio do
capĂ­tulo. Lembre-se de que os objetos da classe `Random` nos permitem gerar todos os
tipos de valores aleatĂłrios. Para implementar essa simulaĂ§ĂŁo com sucesso, nosso
programa deve tomar as decisĂ”es necessĂĄrias para configurar o jogo para o
usuĂĄrio, bem como responder Ă s entradas do usuĂĄrio.
 

[source, java]
----
include::{programsdir}/MontyHall.java[linhas=1..11]
----
<.> ComeĂ§amos com a instruĂ§ĂŁo `import`
necessĂĄria para usar as classes `Scanner` e `Random`
e, em seguida, definimos a classe `MontyHall`.
<.> No mĂ©todo `main()`, primeiro decidimos qual das trĂȘs portas Ă© a
vencedora. Para isso, instanciamos um objeto `Random` e o usamos para
gerar um nĂșmero aleatĂłrio que seja 0, 1 ou 2, chamando o
mĂ©todo `nextInt()` com um argumento de `3`. PoderĂ­amos ter somado 1 a
esse valor para obter uma escolha aleatĂłria entre 1, 2 ou 3, mas muitos sistemas de contagem
em ciĂȘncia da computaĂ§ĂŁo comeĂ§am com 0 em vez de 1. Podemos muito bem
aceitar isso.
<.> Em seguida, solicitamos que o usuĂĄrio escolha uma das trĂȘs portas
e lemos a escolha.
<.> Por fim, declaramos mais dois valores `int` para acompanhar
qual porta deve ser aberta e qual porta Ă© a alternativa para a qual o
usuĂĄrio pode optar por mudar.

Agora, precisamos lidar com uma sĂ©rie complicada de decisĂ”es. 

[source, java]
----
include::{programsdir}/MontyHall.java[linhas=13..34]
----
<.> Neste
trecho de cĂłdigo, lidamos com a possibilidade de o usuĂĄrio ter
escolhido a porta vencedora. Para seguir as regras do jogo, precisamos
escolher aleatoriamente qual das duas outras portas abrir.
<.> Primeiro, determinamos
quais sĂŁo as outras duas portas e as salvamos em `low` e `high`,
respectivamente.
<.> Em seguida, geramos um nĂșmero aleatĂłrio.
<.> Se o nĂșmero aleatĂłrio
for menor que 0,5, mantemos a porta com o nĂșmero menor como uma opĂ§ĂŁo
alternativa para o usuĂĄrio e abrimos a porta com o nĂșmero maior.
<.> Se o nĂșmero aleatĂłrio for maior ou igual a 0,5, fazemos o contrĂĄrio.

[source, java]
----
include::{programsdir}/MontyHall.java[linhas=35..56]
----
<.> Este bloco `else` abrange o caso em que o jogador *nĂŁo* escolheu a
porta vencedora na primeira vez. Ao contrĂĄrio do segmento de cĂłdigo anterior, nĂŁo
temos mais a opĂ§ĂŁo de escolher qual porta abrir.
<.> Em vez disso, devemos sempre
tornar a porta vencedora a alternativa para o usuĂĄrio escolher. EntĂŁo, simplesmente
determinamos qual porta resta para que possamos abri-la.

[source, java]
----
include::{programsdir}/MontyHall.java[linhas=57..73]
----
<.> Este segmento final de cĂłdigo informa ao usuĂĄrio qual porta foi aberta.
<.> Ele solicita que o usuĂĄrio altere sua decisĂŁo.
<.> Dependendo da
escolha final, o programa informa se o usuĂĄrio ganha ouro ou
porcaria.


=== ConcorrĂȘncia: SeleĂ§ĂŁo

As instruĂ§Ă”es de seleĂ§ĂŁo (`if` e `switch`) parecem ter
pouca relaĂ§ĂŁo com concorrĂȘncia ou paralelismo. A seleĂ§ĂŁo permite que vocĂȘ
escolha entre alternativas, enquanto a concorrĂȘncia diz respeito Ă  interaĂ§ĂŁo
entre diferentes threads de execuĂ§ĂŁo. Na verdade, existem duas
razĂ”es pelas quais a seleĂ§ĂŁo e a concorrĂȘncia estĂŁo profundamente relacionadas entre si.

A primeira razĂŁo Ă© que a seleĂ§ĂŁo Ă© uma das ferramentas mais bĂĄsicas em
Java. Ă impossĂ­vel avanĂ§ar mais do que algumas linhas de cĂłdigo sem
encontrar uma instruĂ§ĂŁo de seleĂ§ĂŁo, geralmente um `if`.
Programas concorrentes nĂŁo estĂŁo isentos dessa dependĂȘncia de instruĂ§Ă”es `if`
. Tomar decisĂ”es estĂĄ no cerne de todas as linguagens de programaĂ§ĂŁo
executadas em todos os computadores.

A segunda razĂŁo, mais preocupante, estĂĄ relacionada a um problema em
alguns programas concorrentes chamado de _condiĂ§ĂŁo de corrida_, que Ă© discutido
em detalhes em <<sincronizaĂ§ĂŁo#sincronizaĂ§ĂŁo>>. Lembre-se: um dos
maiores desafios da programaĂ§ĂŁo de computadores Ă© pensar de uma
maneira completamente sequencial e lĂłgica. Cada linha de cĂłdigo Ă© executada uma
apĂłs a outra. Adicionar instruĂ§Ă”es `if` significa que parte do cĂłdigo Ă©
executada apenas se uma condiĂ§ĂŁo for verdadeira e ignorada caso contrĂĄrio. Considere o
seguinte fragmento de cĂłdigo.

[source,java]
----
if (!fosforo.saoAcessos() && !faiscasVoando) {
    despensa.entrar();
    dinamite.desembrulhar();
}
----

Nesta instruĂ§ĂŁo `if`, um agente imaginĂĄrio sĂł entra na sala de armazenamento
e desembala a dinamite se os fĂłsforos nĂŁo estiverem acesos e nĂŁo houver
faĂ­scas voando. Quando a execuĂ§ĂŁo chega Ă  primeira linha dentro do bloco `if`
, temos certeza de que `fosforo.saoAcessos()` retornou `false` e
`faiscasVoando` Ă© `false`. Essa Ă© uma verificaĂ§ĂŁo Ășnica. Se a primeira coisa
que acontecer dentro do bloco `if` for um cĂłdigo que acenda os fĂłsforos, o Java
*nĂŁo* sairĂĄ da instruĂ§ĂŁo `if`.

Como sempre, o programador Ă© responsĂĄvel por criar uma instruĂ§ĂŁo `if`
que faĂ§a sentido. Ă possĂ­vel que entrar na sala de armazenamento ou
desembalar a dinamite faĂ§a faĂ­scas voarem ou os fĂłsforos pegarem fogo
espontaneamente, mas isso parece improvĂĄvel. Se os objetos `despensa` e
`dinamite` tivessem sido escritos por outras pessoas, esperarĂ­amos que sua
documentaĂ§ĂŁo explicasse efeitos colaterais incomuns desse tipo. Em um
programa sequencial, o programador pode ter razoĂĄvel certeza de que Ă©
seguro desembalar a dinamite.

Considere outro fragmento de cĂłdigo.

[source,java]
----
fosforos.acender();
faiscasVoando = fogosDeArtificio.acender(fosforos);
----

Este cĂłdigo parece acender os fĂłsforos e, em seguida, usar os fĂłsforos acesos para
acender alguns fogos de artifĂ­cio. Presumivelmente, se o processo for bem-sucedido,
`faiscasVoando` terĂĄ o valor `true`. Este cĂłdigo Ă© razoĂĄvel e
potencialmente Ăștil. Se vocĂȘ estivesse comemorando o 4 de julho ou precisasse
sinalizar para um helicĂłptero que passa para resgatĂĄ-lo de uma ilha deserta,
acender fogos de artifĂ­cio poderia ser uma Ăłtima ideia. Este cĂłdigo de acendimento de fogos de artifĂ­cio
poderia ocorrer antes ou depois do cĂłdigo de desembalagem da dinamite, mas, em um programa sequencial
, a proteĂ§ĂŁo da instruĂ§ĂŁo `if` impede que nossa heroĂ­na seja explodida se
ela tentar desembalar a dinamite com fogos de artifĂ­cio acesos.

Em um programa concorrente, nada Ă© garantido. Outra thread de execuĂ§ĂŁo
pode estar operando exatamente ao mesmo tempo. Ă como se nossa heroĂ­na estivesse tentando
desembalar a dinamite enquanto o vilĂŁo acende fogos de artifĂ­cio e os joga
na sala de armazenamento. Se a thread de execuĂ§ĂŁo chegar Ă  instruĂ§ĂŁo `if`
e se certificar de que os fĂłsforos nĂŁo estĂŁo acesos e que nĂŁo hĂĄ
faĂ­scas voando, ela continua adiante. Se faĂ­scas comeĂ§arem a voar apĂłs essa
verificaĂ§ĂŁo, ela ainda assim continua, alheia ao fato. Mesmo que
esse risco de explosĂŁo exista, ele depende do sincronismo das duas (ou
mais) threads de execuĂ§ĂŁo simultĂąneas. Pode ser possĂ­vel executar um
programa 1.000 vezes sem nenhum problema. Mas se o sincronismo estiver errado na
1.001^ÂȘ^ vez, *BOOM!*

Nesse ponto, vocĂȘ nĂŁo precisa se preocupar com valores dentro de suas instruĂ§Ă”es `if`
sendo alterados por outros segmentos de cĂłdigo, mas esse problema estĂĄ
no cerne do motivo pelo qual a programaĂ§ĂŁo concorrente pode ser tĂŁo difĂ­cil. Quer
vocĂȘ esteja programando de forma concorrente ou nĂŁo, Ă© importante ter
em mente as suposiĂ§Ă”es que seu cĂłdigo faz e a maneira como diferentes partes do
seu programa interagem entre si.

=== ExercĂ­cios
*Problemas conceituais*

. Considerando que _x_, _y_ e _z_ sĂŁo
proposiĂ§Ă”es na lĂłgica booleana, elabore uma tabela de verdade para a expressĂŁo
ÂŹ(_x_ â§ ÂŹ__y__) â ÂŹ__z__.
//HĂĄ uma anomalia no AsciiDoctor na prĂłxima linha se os espaĂ§os dentro dos parĂȘnteses externos forem removidos.
. Qual Ă© o valor da expressĂŁo booleana ÂŹ( (T â F) â§ ÂŹ(F âš T) )?
. O cĂĄlculo para determinar o ano bissexto apresentado em
<<leapYearExample>> usa trĂȘs instruĂ§Ă”es `if` e trĂȘs
instruĂ§Ă”es `else`. Escreva o cĂĄlculo do ano bissexto usando um Ășnico `if`
e um Ășnico `else`. Sinta-se Ă  vontade para usar operadores lĂłgicos, como `||`
e `&&`.
.  O operador XOR (`^`) Ă© Ăștil para combinar valores `boolean`, mas
pode ser substituĂ­do por um operador *relacional* mais comumente usado em
Java. Qual deles?
. As leis de De Morgan sĂŁo as seguintes, mostrando que o processo de
negar uma clĂĄusula transforma um AND em um OR e vice-versa.
+
ÂŹ(_x_ â§ _y_) = ÂŹ__x__ âš ÂŹ__y__ +
ÂŹ(_x_ âš _y_) = ÂŹ__x__ â§ ÂŹ__y__
+
Crie tabelas de verdade para verificar ambas as afirmaĂ§Ă”es.
. Use as leis de De Morgan apresentadas acima para reescrever a seguinte afirmaĂ§ĂŁo
em Java como uma afirmaĂ§ĂŁo equivalente que nĂŁo contenha negaĂ§Ă”es.
+
[source,java]
----
boolean valor = !((x != 4) && (y < 2));
----
. Considere o seguinte fragmento de cĂłdigo.
+
[source,java]
----
int x = 5;
int y = 3;
if (y > 10 && (x = 10) > 5) {
    ++y;
}
System.out.println(âx: â + x);
System.out.println(ây: â + y);
----
+
Qual Ă© a saĂ­da? A saĂ­da muda se a condiĂ§ĂŁo da instruĂ§ĂŁo `if`
for alterada para `y > 10 & (x = 10) > 5`? Por quĂȘ?
. Considere o seguinte fragmento de cĂłdigo.
+
[source,java]
----
int a = 7;
if (a++ == 7) {
    System.out.println(âSeteâ);
} else {
    System.out.println(âNĂŁo Ă© seteâ);
}
----
+
Qual Ă© a saĂ­da? A saĂ­da muda se a condiĂ§ĂŁo da instruĂ§ĂŁo `if`
for alterada para `++a == 7`? Por quĂȘ? +
ObservaĂ§ĂŁo: geralmente Ă© aconselhĂĄvel
evitar instruĂ§Ă”es de incremento, decremento e atribuiĂ§ĂŁo na condiĂ§ĂŁo
de uma instruĂ§ĂŁo `if`, devido Ă  confusĂŁo que isso pode causar.


*ExercĂ­cios de ProgramaĂ§ĂŁo*

. Escreva programas que:
..  Leiam dois valores do tipo `double` e imprimam o
maior dos dois.
..  Leiam *trĂȘs* valores do tipo `double` e imprimam o maior dos trĂȘs.
ObservaĂ§ĂŁo: VocĂȘ deve usar instruĂ§Ă”es `if` aninhadas.
. [[coinNamesExercise]] Escreva programas que:
..  Leiam um valor `int` do usuĂĄrio especificando um determinado nĂșmero de
centavos. Use instruĂ§Ă”es `if` para imprimir o nome da moeda correspondente
na moeda dos EUA de acordo com a tabela abaixo. Se o valor nĂŁo
corresponder a nenhuma moeda, imprima `no coin`.
+
[.center%autowidth%unbreakable,cols=â^,^â,]
|===============
|Centavos |Moeda

|1 |penny
|5 |nickel
|10 |dime
|25 |quarter
|50 |half-dollar
|100 |dollar
|===============
..  Leia um valor `String` do usuĂĄrio que forneĂ§a um dos 6 nomes de moedas
apresentados na tabela acima. Use instruĂ§Ă”es `if` para imprimir o
nĂșmero correspondente de centavos para a entrada. Se o nome nĂŁo corresponder a
nenhuma moeda, imprima `moeda desconhecida`.
. Reimplemente ambas as partes de <<coinNamesExercise>> usando instruĂ§Ă”es `switch` em vez de instruĂ§Ă”es `if`.
. [[ordinalNumbersExercise]] Expanda o programa apresentado em
<<ordinalNumbersExample>> para fornecer os sufixos corretos (sempre
â`th`â) para nĂșmeros que terminam em 11, 12 e 13. Use o operador mĂłdulo
para encontrar os dois Ășltimos dĂ­gitos do nĂșmero. Usando uma instruĂ§ĂŁo `if`
, uma instruĂ§ĂŁo `switch` ou uma combinaĂ§ĂŁo, verifique esses trĂȘs
casos antes de passar para os casos normais.
. Na parte inferior de <<_instruĂ§Ă”es_switch>>, usamos uma
instruĂ§ĂŁo `switch` para determinar a localizaĂ§ĂŁo de vĂĄrios cĂłdigos de ĂĄrea no
estado de Nova York. Escreva um fragmento de cĂłdigo equivalente usando instruĂ§Ă”es `if`-`else`
em vez disso.
. Cada membro do seu clube secreto tem um nĂșmero de identificaĂ§ĂŁo. Esses nĂșmeros de identificaĂ§ĂŁo
estĂŁo entre 1 e 1.000.000 e tĂȘm duas caracterĂ­sticas especiais: sĂŁo
mĂșltiplos de 7 e todos terminam com um 3 na casa das unidades. Por exemplo,
63 Ă© o menor desses valores, e 999.943 Ă© o maior desses valores.
Escreva um programa que solicite ao usuĂĄrio um valor `int`, leia-o
e, em seguida, indique se ele poderia ou nĂŁo ser usado como um nĂșmero de identificaĂ§ĂŁo. ObservaĂ§ĂŁo: vocĂȘ
precisa usar o operador mĂłdulo de duas maneiras diferentes para testar o valor
corretamente.
. De acordo com o Plano de NumeraĂ§ĂŁo Norte-Americano (NANP) usado pelos
Estados Unidos, CanadĂĄ e vĂĄrios paĂ­ses menores, um nĂșmero de telefone vĂĄlido
tem o formato `XYY-XYY-YYYY`, onde `X` Ă© qualquer dĂ­gito
de 2 a 9 e `Y` Ă© qualquer dĂ­gito de 0 a 9. Escreva um programa que leia uma `String`
do usuĂĄrio e verifique se Ă© um nĂșmero de telefone vĂĄlido segundo o NANP. O
comprimento total da `String` deve ser 12. O quarto e o oitavo
caracteres da `String` (com Ă­ndices `3` e `7`) devem ser hĂ­fens
(`-`), e todos os dĂ­gitos restantes devem estar no intervalo correto. Use
o mĂ©todo `charAt()` da classe `String` para obter o valor `char` em
cada Ă­ndice. ObservaĂ§ĂŁo: hĂĄ vĂĄrias maneiras de estruturar as instruĂ§Ă”es `if`
que vocĂȘ precisa usar, mas o nĂșmero de condiĂ§Ă”es pode se tornar
grande. (23 ou mais!)
. Reimplemente a soluĂ§ĂŁo para o programa Monty Hall apresentada em
<<SoluĂ§ĂŁo: Monty Hall>> usando `JOptionPane` para gerar GUIs para
entrada e saĂ­da.
